s/→/\\rightarrow /g
s/←/\\leftarrow /g
s/↑/\\uparrow /g
s/↓/\\downarrow /g
s/↗/\\nearrow /g
s/↘/\\searrow /g
s/↔/\\leftrightarrow /g
s/⇒/\\Rightarrow /g
s/⇐/\\Leftarrow /g
s/⇑/\\Uparrow /g
s/⇓/\\Downarrow /g
s/⇔/\\Leftrightarrow /g
s/⇀/\\rightharpoonup /g
s/↦/\\mapsto /g
s/⟨/\\langle /g
s/⟩/\\rangle /g
s/⟦/\\llbracket /g
s/⟧/\\rrbracket /g
s/❴/\\{ /g
s/❵/\\} /g
s/⟅/\\lbag /g
s/⟆/\\rbag /g
s/–/--/g
s/—/---/g
s/⋅/\\cdotp /g
s/∶/: /g
s/∷/:: /g
s/…/\\ldots /g
s/∘/\\circ /g
s/⊙/\\odot /g
s/⌾/\\circledcirc /g
s/‖/\\| /g
s/★/\\star /g
s/♯/\\sharp /g
s/♭/\\flat /g
s/♮/\\natural /g
s/×/\\times /g
s/⊕/\\oplus /g
s/⊖/\\ominus /g
s/⊗/\\otimes /g
s/◇/\\diamond /g
s/⟐/\\diamonddot /g
s/∎/\\blacksquare /g
s/∈/\\in /g
s/∀/\\forall /g
s/∃/\\exists /g
s/⊢/\\vdash /g
s/⊨/\\models /g
s/∨/\\vee /g
s/∧/\\wedge /g
s/⊥/\\bot /g
s/⊤/\\top /g
s/¬/\\neg /g
s/∪/\\cup /g
s/∩/\\cap /g
s/⨄/\\uplus /g
s/⋃/\\bigcup /g
s/⋂/\\bigcap /g
s/≤/\\leq /g
s/≥/\\geq /g
s/⊑/\\sqsubseteq /g
s/⊒/\\sqsupseteq /g
s/⊏/\\sqsubset /g
s/⊐/\\sqsupset /g
s/⋤/\\sqsubsetneq /g
s/⊔/\\sqcup /g
s/⊓/\\sqcap /g
s/⨆/\\bigsqcup /g
s/⋈/\\bowtie /g
s/∞/\\infty /g
s/≪/\\ll /g
s/≫/\\gg /g
s/≡/\\equiv /g
s/≃/\\simeq /g
s/≈/\\approx /g
s/≔/\\coloneqq /g
s/⩴/\\Coloneqq /g
s/≠/\\neq /g
s/≜/\\triangleq /g
s/₊/_+ /g
s/₋/_- /g
s/₍/( /g
s/₎/) /g
s/⁺/\^+ /g
s/⁻/\^- /g
s/⁽/\^( /g
s/⁾/\^) /g
s/‣/\\blacktriangleright /g
s/Α/\\Alpha /g
s/Β/\\Beta /g
s/Γ/\\Gamma /g
s/Δ/\\Delta /g
s/Ε/\\Epsilon /g
s/Ζ/\\Zeta /g
s/Η/\\Eta /g
s/Θ/\\Theta /g
s/Ι/\\Iota /g
s/Κ/\\Kappa /g
s/Λ/\\Lambda /g
s/Μ/\\Mu /g
s/Ν/\\Nu /g
s/Ξ/\\Xi /g
s/Ο/\\Omicron /g
s/Π/\\Pi /g
s/Ρ/\\Rho /g
s/ϴ/\\varSigma /g
s/Σ/\\Sigma /g
s/Τ/\\Tau /g
s/Υ/\\Upsilon /g
s/Φ/\\Phi /g
s/Χ/\\Chi /g
s/Ψ/\\Psi /g
s/Ω/\\Omega /g
s/∇/\\Nabla /g
s/α/\\alpha /g
s/β/\\beta /g
s/γ/\\gamma /g
s/δ/\\delta /g
s/ε/\\epsilon /g
s/ζ/\\zeta /g
s/η/\\eta /g
s/θ/\\theta /g
s/ι/\\iota /g
s/κ/\\kappa /g
s/λ/\\lambda /g
s/μ/\\mu /g
s/ν/\\nu /g
s/ξ/\\xi /g
s/ο/\\omicron /g
s/π/\\pi /g
s/ρ/\\rho /g
s/ς/\\varsigma /g
s/σ/\\sigma /g
s/τ/\\tau /g
s/υ/\\upsilon /g
s/φ/\\phi /g
s/χ/\\chi /g
s/ψ/\\psi /g
s/ω/\\omega /g
s/∂/\\nabla /g
s/ϵ/\\varepsilon /g
s/ϑ/\\vartheta /g
s/ϰ/\\varkappa /g
s/ϕ/\\varphi /g
s/ϱ/\\varrho /g
s/ϖ/\\varpi /g
s/₀/_0 /g
s/₁/_1 /g
s/₂/_2 /g
s/₃/_3 /g
s/₄/_4 /g
s/₅/_5 /g
s/₆/_6 /g
s/₇/_7 /g
s/₈/_8 /g
s/₉/_9 /g
s/⁰/\^0 /g
s/¹/\^1 /g
s/²/\^2 /g
s/³/\^3 /g
s/⁴/\^4 /g
s/⁵/\^5 /g
s/⁶/\^6 /g
s/⁷/\^7 /g
s/⁸/\^8 /g
s/⁹/\^9 /g
s/℘/\\wp /g
s/𝒜/\\mathcal{A} /g
s/ℬ/\\mathcal{B} /g
s/𝒞/\\mathcal{C} /g
s/𝒟/\\mathcal{D} /g
s/ℰ/\\mathcal{E} /g
s/ℱ/\\mathcal{F} /g
s/𝒢/\\mathcal{G} /g
s/ℋ/\\mathcal{H} /g
s/ℐ/\\mathcal{I} /g
s/𝒥/\\mathcal{J} /g
s/𝒦/\\mathcal{K} /g
s/ℒ/\\mathcal{L} /g
s/ℳ/\\mathcal{M} /g
s/𝒩/\\mathcal{N} /g
s/𝒪/\\mathcal{O} /g
s/𝒫/\\mathcal{P} /g
s/𝒬/\\mathcal{Q} /g
s/ℛ/\\mathcal{R} /g
s/𝒮/\\mathcal{S} /g
s/𝒯/\\mathcal{T} /g
s/𝒰/\\mathcal{U} /g
s/𝒱/\\mathcal{V} /g
s/𝒲/\\mathcal{W} /g
s/𝒳/\\mathcal{X} /g
s/𝒴/\\mathcal{Y} /g
s/𝒵/\\mathcal{Z} /g
s/𝒶/\\mathcal{a} /g
s/𝒷/\\mathcal{b} /g
s/𝒸/\\mathcal{c} /g
s/𝒹/\\mathcal{d} /g
s/ℯ/\\mathcal{e} /g
s/𝒻/\\mathcal{f} /g
s/ℊ/\\mathcal{g} /g
s/𝒽/\\mathcal{h} /g
s/𝒾/\\mathcal{i} /g
s/𝒿/\\mathcal{j} /g
s/𝓀/\\mathcal{k} /g
s/𝓁/\\mathcal{l} /g
s/𝓂/\\mathcal{m} /g
s/𝓃/\\mathcal{n} /g
s/ℴ/\\mathcal{o} /g
s/𝓅/\\mathcal{p} /g
s/𝓆/\\mathcal{q} /g
s/𝓇/\\mathcal{r} /g
s/𝓈/\\mathcal{s} /g
s/𝓉/\\mathcal{t} /g
s/𝓊/\\mathcal{u} /g
s/𝓋/\\mathcal{v} /g
s/𝓌/\\mathcal{w} /g
s/𝓍/\\mathcal{x} /g
s/𝓎/\\mathcal{y} /g
s/𝓏/\\mathcal{z} /g
s/𝔸/\\mathbb{A} /g
s/𝔹/\\mathbb{B} /g
s/ℂ/\\mathbb{C} /g
s/𝔻/\\mathbb{D} /g
s/𝔼/\\mathbb{E} /g
s/𝔽/\\mathbb{F} /g
s/𝔾/\\mathbb{G} /g
s/ℍ/\\mathbb{H} /g
s/𝕀/\\mathbb{I} /g
s/𝕁/\\mathbb{J} /g
s/𝕂/\\mathbb{K} /g
s/𝕃/\\mathbb{L} /g
s/𝕄/\\mathbb{M} /g
s/ℕ/\\mathbb{N} /g
s/𝕆/\\mathbb{O} /g
s/ℙ/\\mathbb{P} /g
s/ℚ/\\mathbb{Q} /g
s/ℝ/\\mathbb{R} /g
s/𝕊/\\mathbb{S} /g
s/𝕋/\\mathbb{T} /g
s/𝕌/\\mathbb{U} /g
s/𝕍/\\mathbb{V} /g
s/𝕎/\\mathbb{W} /g
s/𝕏/\\mathbb{X} /g
s/𝕐/\\mathbb{Y} /g
s/ℤ/\\mathbb{Z} /g
s/𝕒/\\mathbb{a} /g
s/𝕓/\\mathbb{b} /g
s/𝕔/\\mathbb{c} /g
s/𝕕/\\mathbb{d} /g
s/𝕖/\\mathbb{e} /g
s/𝕗/\\mathbb{f} /g
s/𝕘/\\mathbb{g} /g
s/𝕙/\\mathbb{h} /g
s/𝕚/\\mathbb{i} /g
s/𝕛/\\mathbb{j} /g
s/𝕜/\\mathbb{k} /g
s/𝕝/\\mathbb{l} /g
s/𝕞/\\mathbb{m} /g
s/𝕟/\\mathbb{n} /g
s/𝕠/\\mathbb{o} /g
s/𝕡/\\mathbb{p} /g
s/𝕢/\\mathbb{q} /g
s/𝕣/\\mathbb{r} /g
s/𝕤/\\mathbb{s} /g
s/𝕥/\\mathbb{t} /g
s/𝕦/\\mathbb{u} /g
s/𝕧/\\mathbb{v} /g
s/𝕨/\\mathbb{w} /g
s/𝕩/\\mathbb{x} /g
s/𝕪/\\mathbb{y} /g
s/𝕫/\\mathbb{z} /g
s/ₐ/_a /g
s/ₑ/_e /g
s/ₕ/_h /g
s/ᵢ/_i /g
s/ⱼ/_j /g
s/ₖ/_k /g
s/ₗ/_l /g
s/ₘ/_m /g
s/ₙ/_n /g
s/ₒ/_o /g
s/ₚ/_p /g
s/ᵣ/_r /g
s/ₛ/_s /g
s/ₜ/_t /g
s/ᵤ/_u /g
s/ᵥ/_v /g
s/ₓ/_x /g
s/ᴬ/\^A /g
s/ᴮ/\^B /g
s/ᴰ/\^D /g
s/ᴱ/\^E /g
s/ᴳ/\^G /g
s/ᴴ/\^H /g
s/ᴵ/\^I /g
s/ᴶ/\^J /g
s/ᴷ/\^K /g
s/ᴸ/\^L /g
s/ᴹ/\^M /g
s/ᴺ/\^N /g
s/ᴼ/\^O /g
s/ᴾ/\^P /g
s/ᴿ/\^R /g
s/ᵀ/\^T /g
s/ᵁ/\^U /g
s/ⱽ/\^V /g
s/ᵂ/\^W /g
s/ᵃ/\^a /g
s/ᵇ/\^b /g
s/ᶜ/\^c /g
s/ᵈ/\^d /g
s/ᵉ/\^e /g
s/ᶠ/\^f /g
s/ᵍ/\^g /g
s/ʰ/\^h /g
s/ⁱ/\^i /g
s/ʲ/\^j /g
s/ᵏ/\^k /g
s/ˡ/\^l /g
s/ᵐ/\^m /g
s/ⁿ/\^n /g
s/ᵒ/\^o /g
s/ᵖ/\^p /g
s/ʳ/\^r /g
s/ˢ/\^s /g
s/ᵗ/\^t /g
s/ᵘ/\^u /g
s/ᵛ/\^v /g
s/ʷ/\^w /g
s/ˣ/\^x /g
s/ʸ/\^y /g
s/ᶻ/\^z /g
s/ö/\\"o /g
