module UnicodeGen where

import Data.List

type UnicodeRep = String
type EscapeCode = String
type LatexRep = String
type Description = String

main :: IO ()
main = do
  writeFile "unicode.el" genEmacsScript
  writeFile "unicode.vim" genVimScript
  writeFile "latex-unicode.sed" genSedScript

data Code = Code UnicodeRep EscapeCode LatexRep Description

code :: UnicodeRep -> EscapeCode -> Code
code u e = Code u e "" ""

lcode :: UnicodeRep -> EscapeCode -> LatexRep -> Code
lcode u e l = Code u e (l ++ " ") ""

lcodet :: UnicodeRep -> EscapeCode -> LatexRep -> Code
lcodet u e l = Code u e l ""

vimEscape :: String -> String
vimEscape = concatMap escapeChar
  where
    escapeChar :: Char -> String
    escapeChar '|' = "\\|"
    escapeChar c = [c]

emacsEscape :: String -> String
emacsEscape = concatMap escapeChar
  where
    escapeChar :: Char -> String
    escapeChar '\\' = "\\\\"
    escapeChar '\"' = "\\\""
    escapeChar c = [c]

sedEscape :: String -> String
sedEscape = concatMap escapeChar
  where
    escapeChar :: Char -> String
    escapeChar '\\' = "\\\\"
    escapeChar '/'  = "\\/"
    escapeChar '&'  = "\\&"
    escapeChar '$'  = "\\$"
    escapeChar '.'  = "\\."
    escapeChar '*'  = "\\*"
    escapeChar '^'  = "\\^"
    escapeChar '['  = "\\["
    escapeChar ']'  = "\\]"
    escapeChar c    = [c]

genVimScript :: String
genVimScript = do
  code <- codes
  command code
  where
    command :: Code -> String
    command (Code u e _ _) = "noremap! " ++ vimEscape ("\\" ++ e) ++ " " ++ vimEscape u ++ "\n"

genEmacsScript :: String
genEmacsScript = concat $ intersperse "\n"
  [ "(quail-define-package"
  , " \"darais\""
  , " \"UTF-32\""
  , " \"DaraisInput\""
  , " t"
  , " \"David Darais's personal input codes\""
  , " nil t nil nil nil nil nil nil nil nil t)"
  , "(quail-define-rules"
  , do
      code <- codes
      command code
    ++ ")"
  ]
  where
      command :: Code -> String
      command (Code u e _ _) = " (\"" ++ emacsEscape ("\\" ++ e) ++ "\" \"" ++ emacsEscape u ++ "\")" ++ "\n"

genSedScript :: String
genSedScript = do
  code <- codes
  command code
    where
        command :: Code -> String
        command (Code u _ l _) = 
          if l == "" 
             then ""
             else "s/" ++ sedEscape u ++ "/" ++ sedEscape l ++ "/g\n"

codes :: [Code]
codes = 
  -- Backslash
  [ code "\\"  "\\"

  -- Arrows
  , lcode "→" "->" "\\rightarrow"
  , lcode "←" "<-" "\\leftarrow"
  , lcode "↑" "up" "\\uparrow"
  , lcode "↓" "down" "\\downarrow"
  , lcode "↗" "upr" "\\nearrow"
  , lcode "↘" "downr" "\\searrow"
  , lcode "↔" "<->" "\\leftrightarrow"
  , code "⇄" "iso"
  , code "⇉" "->->"
  , lcode "⇒" "=>" "\\Rightarrow"
  , lcode "⇐" "=<" "\\Leftarrow"
  , lcode "⇑" "Up" "\\Uparrow"
  , lcode "⇓" "Down" "\\Downarrow"
  , code "⇨" "|=>"
  , code "⇦" "|=<"
  , code "⇧" "|=u"
  , code "⇩" "|=d"
  , lcode "⇔" "<=>" "\\Leftrightarrow"
  , code "⇰" "||=>"
  , lcode "⇀" "-\\" "\\rightharpoonup"
  , lcode "↦" "|->" "\\mapsto"
  , code "⇥" "->|"
  , code "⇤" "|<-"
  , code "↠" "->>"
  , code "⇾" "-|>"
  , code "⇿" "<|-|>"
  , code "↝" "~>"
  , code "↜" "~<"
  , code "⇝" "~~>"
  , code "↯" "zd"

  -- Brackets
  , lcode "⟨" "<" "\\langle"
  , lcode "⟩" ">" "\\rangle"
  , code "⟪" "<<"
  , code "⟫" ">>"
  , code "⦉" "<|"
  , code "⦊" ">|"
  , code "⦑" "<."
  , code "⦒" ">."
  , code "«" "<\""
  , code "»" ">\""
  , code "⟮" "("
  , code "⟯" ")"
  , code "⸨" "(("
  , code "⸩" "))"
  , code "⦇" "(|"
  , code "⦈" ")|"
  , code "⦅" "c("
  , code "⦆" "c)"
  , lcode "⟦" "[[" "\\llbracket"
  , lcode "⟧" "]]" "\\rrbracket"
  , code "⟬" "[|"
  , code "⟭" "]|"
  , code "⌈" "tL"
  , code "⌉" "tR"
  , code "⌊" "bL"
  , code "⌋" "bR"
  , code "⸢" "tl"
  , code "⸣" "tr"
  , code "⸤" "bl"
  , code "⸥" "br"
  , lcode "❴" "bld{" "\\{"
  , lcode "❵" "bld}" "\\}"
  , code "⦃" "{{"
  , code "⦄" "}}"
  , code "⧘" "z{"
  , code "⧙" "z}"
  , code "⧚" "zz{"
  , code "⧛" "zz}"
  , lcode "⟅" "s{" "\\lbag"
  , lcode "⟆" "s}" "\\rbag"

  -- Quotes
  , code "“" "``"
  , code "”" "''"
  , lcodet "–" "--" "--"
  , lcodet "—" "---" "---"

  -- Operators
  , lcode "⋅" "." "\\cdotp"
  , lcode "∶" ":" ":"
  , code "∵" ".:"
  , lcode "∷" "::" "::"
  , lcode "…" "..." "\\ldots"
  , lcode "∘" "o" "\\circ"
  , lcode "⊙" "o." "\\odot"
  , lcode "⌾" "oo" "\\circledcirc"
  , code "⦂" "o:"
  , code "⨟" "o;"
  , code "¦" "|:"
  , lcode "‖" "||" "\\|"
  , code "∅" "O/"
  , code "⋆" "*"
  , lcode "★" "star" "\\star"
  , lcode "♯" "#" "\\sharp"
  , code "𝄪" "##"
  , lcode "♭" "b" "\\flat"
  , lcode "♮" "n" "\\natural"
  , code "⋕" "=||"
  , code "⁇" "??"
  , code "⧺" "++"
  , lcode "×" "x" "\\times"
  , code "⨯" "xx"
  , code "⤨" "swap"
  , lcode "⊕" "o+" "\\oplus"
  , lcode "⊖" "o-" "\\ominus"
  , lcode "⊗" "ox" "\\otimes"
  , code "⧀" "o<"
  , code "⎊" "ot"
  , lcode "◇" "d" "\\diamond"
  , lcode "⟐" "d." "\\diamonddot"
  , code "□" "s"
  , code "⊞" "s+"
  , code "⊟" "s-"
  , code "⊠" "sx"
  , code "⊡" "s."
  , lcode "∎" "qed" "\\blacksquare"
  , code "⌿" "-/"
 
  -- Logic
  , lcode "∈" "in" "\\in"
  , code "⋵" "in."
  , code "∉" "in/"
  , code "∋" "co"
  , code "⋿" "mem"
  , lcode "∀" "all" "\\forall"
  , lcode "∃" "ex" "\\exists"
  , lcode "⊢" "|-" "\\vdash"
  , lcode "⊨" "|=" "\\models"
  , lcode "∨" "or" "\\vee"
  , lcode "∧" "and" "\\wedge"
  , code "⋎" "sor"
  , code "⋏" "sand"
  , lcode "⊥" "bot" "\\bot"
  , lcode "⊤" "top" "\\top"
  , lcode "¬" "neg" "\\neg"
 
  -- Orders
  , code "⊆" "s<="
  , code "⊇" "s>="
  , lcode "∪" "union" "\\cup"
  , lcode "∩" "inter" "\\cap"
  , code "⊍" "u."
  , lcode "⨄" "u+" "\\uplus"
  , lcode "⋃" "Union" "\\bigcup"
  , lcode "⋂" "Inter" "\\bigcap"
  , lcode "≤" "<=" "\\leq"
  , lcode "≥" ">=" "\\geq"
  , code "⋚" "<=>="
  , lcode "⊑" "sq<=" "\\sqsubseteq"
  , lcode "⊒" "sq>=" "\\sqsupseteq"
  , lcode "⊏" "sq<" "\\sqsubset"
  , lcode "⊐" "sq>" "\\sqsupset"
  , lcode "⋤" "sq<=/" "\\sqsubsetneq"
  , lcode "⊔" "join" "\\sqcup"
  , lcode "⊓" "meet" "\\sqcap"
  , lcode "⨆" "Join" "\\bigsqcup"
  , lcode "⋈" "bow" "\\bowtie"
  , lcode "∞" "inf" "\\infty"
  , code "≺" "c<"
  , code "≻" "c>"
  , code "≼" "c<="
  , code "≽" "c>="
  , code "⊴" "t<="
  , code "⊵" "t>="
  , code "⋬" "t<=/"
  , code "⋭" "t>=/"
  , code "⩻" "<?"
  , code "⩼" ">?"
  , code "⧼" "y<"
  , code "⧽" "y>"
  , code "‹" "<1"
  , code "›" ">1"
  , lcode "≪" "<2" "\\ll"
  , lcode "≫" ">2" "\\gg"
  , code "≫=" ">>="
  , code "≪=" "<<="
 
  -- Equality
  , lcode "≡" "==" "\\equiv"
  , lcode "≃" "~=" "\\simeq"
  , lcode "≈" "~~" "\\approx"
  , lcode "≔" ":=" "\\coloneqq"
  , lcode "⩴" "::=" "\\Coloneqq"
  , lcode "≠" "=/" "\\neq"
  , code "≢" "==/"
  , code "≟" "=?"
  , lcode "≜" "=t" "\\triangleq"
 
  -- Subscripts
  , lcode "₊" "_+" "_+"
  , lcode "₋" "_-" "_-"
  , lcode "₍" "_(" "("
  , lcode "₎" "_)" ")"
  
  -- Superscripts
  , lcode "⁺" "^+" "^+"
  , lcode "⁻" "^-" "^-"
  , lcode "⁽" "^(" "^("
  , lcode "⁾" "^)" "^)"
  , code "˚" "^^o"

  -- Markup
  , code "¶" "PP"
  , code "␣" "_"
  , code "§" "SS"
 
  -- Bullets
  , code "•" "bu"
  , code "◦" "buw"
  , code "⁃" "buh"
  , lcode "‣" "but" "\\blacktriangleright"
 
  -- Triangles
  , code "◁" "trl"
  , code "△" "tru"
  , code "▷" "trr"
  , code "▽" "trd"
 
  -- OK
  , code "✓" "yes"
  , code "✗" "no"

  -- Greek Normal
  , lcode "Α" "Alpha" "\\Alpha"
  , lcode "Β" "Beta" "\\Beta"
  , lcode "Γ" "Gamma" "\\Gamma"
  , lcode "Δ" "Delta" "\\Delta"
  , lcode "Ε" "Epsilon" "\\Epsilon"
  , lcode "Ζ" "Zeta" "\\Zeta"
  , lcode "Η" "Eta" "\\Eta"
  , lcode "Θ" "Theta" "\\Theta"
  , lcode "Ι" "Iota" "\\Iota"
  , lcode "Κ" "Kappa" "\\Kappa"
  , lcode "Λ" "Lambda" "\\Lambda"
  , lcode "Μ" "Mu" "\\Mu"
  , lcode "Ν" "Nu" "\\Nu"
  , lcode "Ξ" "Xi" "\\Xi"
  , lcode "Ο" "Omicron" "\\Omicron"
  , lcode "Π" "Pi" "\\Pi"
  , lcode "Ρ" "Rho" "\\Rho"
  , lcode "ϴ" "varSigma" "\\varSigma"
  , lcode "Σ" "Sigma" "\\Sigma"
  , lcode "Τ" "Tau" "\\Tau"
  , lcode "Υ" "Upsilon" "\\Upsilon"
  , lcode "Φ" "Phi" "\\Phi"
  , lcode "Χ" "Chi" "\\Chi"
  , lcode "Ψ" "Psi" "\\Psi"
  , lcode "Ω" "Omega" "\\Omega"
  , lcode "∇" "Nabla" "\\Nabla"
                                      
  , lcode "α" "alpha" "\\alpha"
  , lcode "β" "beta" "\\beta"
  , lcode "γ" "gamma" "\\gamma"
  , lcode "δ" "delta" "\\delta"
  , lcode "ε" "epsilon" "\\epsilon"
  , lcode "ζ" "zeta" "\\zeta"
  , lcode "η" "eta" "\\eta"
  , lcode "θ" "theta" "\\theta"
  , lcode "ι" "iota" "\\iota"
  , lcode "κ" "kappa" "\\kappa"
  , lcode "λ" "lambda" "\\lambda"
  , lcode "μ" "mu" "\\mu"
  , lcode "ν" "nu" "\\nu"
  , lcode "ξ" "xi" "\\xi"
  , lcode "ο" "omicron" "\\omicron"
  , lcode "π" "pi" "\\pi"
  , lcode "ρ" "rho" "\\rho"
  , lcode "ς" "varsigma" "\\varsigma"
  , lcode "σ" "sigma" "\\sigma"
  , lcode "τ" "tau" "\\tau"
  , lcode "υ" "upsilon" "\\upsilon"
  , lcode "φ" "phi" "\\phi"
  , lcode "χ" "chi" "\\chi"
  , lcode "ψ" "psi" "\\psi"
  , lcode "ω" "omega" "\\omega"
  , lcode "∂" "nabla" "\\nabla"
                                      
  , lcode "ϵ" "varepsilon" "\\varepsilon"
  , lcode "ϑ" "vartheta" "\\vartheta"
  , lcode "ϰ" "varkappa" "\\varkappa"
  , lcode "ϕ" "varphi" "\\varphi"
  , lcode "ϱ" "varrho" "\\varrho"
  , lcode "ϖ" "varpi" "\\varpi"

  -- Greek Bold
  , code "𝚨" "bldAlpha"
  , code "𝚩" "bldBeta"
  , code "𝚪" "bldGamma"
  , code "𝚫" "bldDelta"
  , code "𝚬" "bldEpsilon"
  , code "𝚭" "bldZeta"
  , code "𝚮" "bldEta"
  , code "𝚯" "bldTheta"
  , code "𝚰" "bldIota"
  , code "𝚱" "bldKappa"
  , code "𝚲" "bldLambda"
  , code "𝚳" "bldMu"
  , code "𝚴" "bldNu"
  , code "𝚵" "bldXi"
  , code "𝚶" "bldOmicron"
  , code "𝚷" "bldPi"
  , code "𝚸" "bldRho"
  , code "𝚹" "bldvarSigma"
  , code "𝚺" "bldSigma"
  , code "𝚻" "bldTau"
  , code "𝚼" "bldUpsilon"
  , code "𝚽" "bldPhi"
  , code "𝚾" "bldChi"
  , code "𝚿" "bldPsi"
  , code "𝛀" "bldOmega"
  , code "𝛁" "bldNabla"

  , code "𝛂" "bldalpha"
  , code "𝛃" "bldbeta"
  , code "𝛄" "bldgamma"
  , code "𝛅" "blddelta"
  , code "𝛆" "bldepsilon"
  , code "𝛇" "bldzeta"
  , code "𝛈" "bldldeta"
  , code "𝛉" "bldtheta"
  , code "𝛊" "bldiota"
  , code "𝛋" "bldkappa"
  , code "𝛌" "bldlambda"
  , code "𝛍" "bldmu"
  , code "𝛎" "bldnu"
  , code "𝛏" "bldxi"
  , code "𝛐" "bldomicron"
  , code "𝛑" "bldpi"
  , code "𝛒" "bldrho"
  , code "𝛓" "bldvarsigma"
  , code "𝛔" "bldsigma"
  , code "𝛕" "bldtau"
  , code "𝛖" "bldupsilon"
  , code "𝛗" "bldphi"
  , code "𝛘" "bldchi"
  , code "𝛙" "bldpsi"
  , code "𝛚" "bldomega"
  , code "𝛛" "bldnabla"

  , code "𝛜" "bvarepsilon"
  , code "𝛝" "bvartheta"
  , code "𝛞" "bvarkappa"
  , code "𝛟" "bvarphi"
  , code "𝛠" "bvarrho"
  , code "𝛡" "bvarpi"

  -- Greek Italic
  , code "𝛢" "itAlpha"
  , code "𝛣" "itBeta"
  , code "𝛤" "itGamma"
  , code "𝛥" "itDelta"
  , code "𝛦" "itEpsilon"
  , code "𝛧" "itZeta"
  , code "𝛨" "itEta"
  , code "𝛩" "itTheta"
  , code "𝛪" "itIota"
  , code "𝛫" "itKappa"
  , code "𝛬" "itLambda"
  , code "𝛭" "itMu"
  , code "𝛮" "itNu"
  , code "𝛯" "itXi"
  , code "𝛰" "itOmicron"
  , code "𝛱" "itPi"
  , code "𝛲" "itRho"
  , code "𝛳" "itvarSigma"
  , code "𝛴" "itSigma"
  , code "𝛵" "itTau"
  , code "𝛶" "itUpsilon"
  , code "𝛷" "itPhi"
  , code "𝛸" "itChi"
  , code "𝛹" "itPsi"
  , code "𝛺" "itOmega"
  , code "𝛻" "itNabla"

  , code "𝛼" "italpha"
  , code "𝛽" "itbeta"
  , code "𝛾" "itgamma"
  , code "𝛿" "itdelta"
  , code "𝜀" "itepsilon"
  , code "𝜁" "itzeta"
  , code "𝜂" "iteta"
  , code "𝜃" "ittheta"
  , code "𝜄" "itiota"
  , code "𝜅" "itkappa"
  , code "𝜆" "itlambda"
  , code "𝜇" "itmu"
  , code "𝜈" "itnu"
  , code "𝜉" "itxi"
  , code "𝜊" "itomicron"
  , code "𝜋" "itpi"
  , code "𝜌" "itrho"
  , code "𝜍" "itvarsigma"
  , code "𝜎" "itsigma"
  , code "𝜏" "ittau"
  , code "𝜐" "itupsilon"
  , code "𝜑" "itphi"
  , code "𝜒" "itchi"
  , code "𝜓" "itpsi"
  , code "𝜔" "itomega"
  , code "𝜕" "itnabla"

  , code "𝜖" "itvarepsilon"
  , code "𝜗" "itvartheta"
  , code "𝜘" "itvarkappa"
  , code "𝜙" "itvarphi"
  , code "𝜚" "itvarrho"
  , code "𝜛" "itvarpi"

  -- Greek Bold Italic
  , code "𝜜" "blditAlpha"
  , code "𝜝" "blditBeta"
  , code "𝜞" "blditGamma"
  , code "𝜟" "blditDelta"
  , code "𝜠" "blditEpsilon"
  , code "𝜡" "blditZeta"
  , code "𝜢" "blditEta"
  , code "𝜣" "blditTheta"
  , code "𝜤" "blditIota"
  , code "𝜥" "blditKappa"
  , code "𝜦" "blditLambda"
  , code "𝜧" "blditMu"
  , code "𝜨" "blditNu"
  , code "𝜩" "blditXi"
  , code "𝜪" "blditOmicron"
  , code "𝜫" "blditPi"
  , code "𝜬" "blditRho"
  , code "𝜭" "blditvarSigma"
  , code "𝜮" "blditSigma"
  , code "𝜯" "blditTau"
  , code "𝜰" "blditUpsilon"
  , code "𝜱" "blditPhi"
  , code "𝜲" "blditChi"
  , code "𝜳" "blditPsi"
  , code "𝜴" "blditOmega"
  , code "𝜵" "blditNabla"

  , code "𝜶" "blditalpha"
  , code "𝜷" "blditbeta"
  , code "𝜸" "blditgamma"
  , code "𝜹" "blditdelta"
  , code "𝜺" "blditepsilon"
  , code "𝜻" "blditzeta"
  , code "𝜼" "blditeta"
  , code "𝜽" "bldittheta"
  , code "𝜾" "blditiota"
  , code "𝜿" "blditkappa"
  , code "𝝀" "blditlambda"
  , code "𝝁" "blditmu"
  , code "𝝂" "blditnu"
  , code "𝝃" "blditxi"
  , code "𝝄" "blditomicron"
  , code "𝝅" "blditpi"
  , code "𝝆" "blditrho"
  , code "𝝇" "blditvarsigma"
  , code "𝝈" "blditsigma"
  , code "𝝉" "bldittau"
  , code "𝝊" "blditupsilon"
  , code "𝝋" "blditphi"
  , code "𝝌" "blditchi"
  , code "𝝍" "blditpsi"
  , code "𝝎" "blditomega"
  , code "𝝏" "blditnabla"

  , code "𝝐" "blditeepsilon"
  , code "𝝑" "blditttheta"
  , code "𝝒" "blditkkappa"
  , code "𝝓" "blditpphi"
  , code "𝝔" "blditrrho"
  , code "𝝕" "blditppi"

  -- Greek Subscript
  , code "ᵦ" "_beta"
  , code "ᵧ" "_gamma"
  , code "ᵨ" "_rho"
  , code "ᵩ" "_phi"
  , code "ᵪ" "_chi"

  -- Greek Superscript
  , code "ᵅ" "^alpha"
  , code "ᵝ" "^beta"
  , code "ᵞ" "^gamma"
  , code "ᵟ" "^delta"
  , code "ᵋ" "^epsilon"
  , code "ᶿ" "^theta"
  , code "ᶥ" "^iota"
  , code "ᶲ" "^Phi"
  , code "ᵠ" "^phi"
  , code "ᵡ" "^chi"

  -- Greek Blackboard Bold
  , code "ℾ" "bbGamma"
  , code "ℽ" "bbgamma"
  , code "ℿ" "bbPi"
  , code "ℼ" "bbpi"
  , code "⅀" "bbSigma"

  -- Numbers Bold
  , code "𝟎" "bld0"
  , code "𝟏" "bld1"
  , code "𝟐" "bld2"
  , code "𝟑" "bld3"
  , code "𝟒" "bld4"
  , code "𝟓" "bld5"
  , code "𝟔" "bld6"
  , code "𝟕" "bld7"
  , code "𝟖" "bld8"
  , code "𝟗" "bld9"

  -- Numbers Blackboard Bold
  , code "𝟘" "bb0"
  , code "𝟙" "bb1"
  , code "𝟚" "bb2"
  , code "𝟛" "bb3"
  , code "𝟜" "bb4"
  , code "𝟝" "bb5"
  , code "𝟞" "bb6"
  , code "𝟟" "bb7"
  , code "𝟠" "bb8"
  , code "𝟡" "bb9"

  -- Numbers Subscript
  , lcode "₀" "_0" "_0"
  , lcode "₁" "_1" "_1"
  , lcode "₂" "_2" "_2"
  , lcode "₃" "_3" "_3"
  , lcode "₄" "_4" "_4"
  , lcode "₅" "_5" "_5"
  , lcode "₆" "_6" "_6"
  , lcode "₇" "_7" "_7"
  , lcode "₈" "_8" "_8"
  , lcode "₉" "_9" "_9"

  -- Numbers Superscript
  , lcode "⁰" "^0" "^0"
  , lcode "¹" "^1" "^1"
  , lcode "²" "^2" "^2"
  , lcode "³" "^3" "^3"
  , lcode "⁴" "^4" "^4"
  , lcode "⁵" "^5" "^5"
  , lcode "⁶" "^6" "^6"
  , lcode "⁷" "^7" "^7"
  , lcode "⁸" "^8" "^8"
  , lcode "⁹" "^9" "^9"

  --  Weierstrass p
  , lcode "℘" "wp" "\\wp"

  -- Roman Bold
  , code "𝐀" "bldA"
  , code "𝐁" "bldB"
  , code "𝐂" "bldC"
  , code "𝐃" "bldD"
  , code "𝐄" "bldE"
  , code "𝐅" "bldF"
  , code "𝐆" "bldG"
  , code "𝐇" "bldH"
  , code "𝐈" "bldI"
  , code "𝐉" "bldJ"
  , code "𝐊" "bldK"
  , code "𝐋" "bldL"
  , code "𝐌" "bldM"
  , code "𝐍" "bldN"
  , code "𝐎" "bldO"
  , code "𝐏" "bldP"
  , code "𝐐" "bldQ"
  , code "𝐑" "bldR"
  , code "𝐒" "bldS"
  , code "𝐓" "bldT"
  , code "𝐔" "bldU"
  , code "𝐕" "bldV"
  , code "𝐖" "bldW"
  , code "𝐗" "bldX"
  , code "𝐘" "bldY"
  , code "𝐙" "bldZ"
  , code "𝐚" "blda"
  , code "𝐛" "bldb"
  , code "𝐜" "bldc"
  , code "𝐝" "bldd"
  , code "𝐞" "blde"
  , code "𝐟" "bldf"
  , code "𝐠" "bldg"
  , code "𝐡" "bldh"
  , code "𝐢" "bldi"
  , code "𝐣" "bldj"
  , code "𝐤" "bldk"
  , code "𝐥" "bldl"
  , code "𝐦" "bldm"
  , code "𝐧" "bldn"
  , code "𝐨" "bldo"
  , code "𝐩" "bldp"
  , code "𝐪" "bldq"
  , code "𝐫" "bldr"
  , code "𝐬" "blds"
  , code "𝐭" "bldt"
  , code "𝐮" "bldu"
  , code "𝐯" "bldv"
  , code "𝐰" "bldw"
  , code "𝐱" "bldx"
  , code "𝐲" "bldy"
  , code "𝐳" "bldz"

  -- Roman Itallic
  , code "𝐴" "itA"
  , code "𝐵" "itB"
  , code "𝐶" "itC"
  , code "𝐷" "itD"
  , code "𝐸" "itE"
  , code "𝐹" "itF"
  , code "𝐺" "itG"
  , code "𝐻" "itH"
  , code "𝐼" "itI"
  , code "𝐽" "itJ"
  , code "𝐾" "itK"
  , code "𝐿" "itL"
  , code "𝑀" "itM"
  , code "𝑁" "itN"
  , code "𝑂" "itO"
  , code "𝑃" "itP"
  , code "𝑄" "itQ"
  , code "𝑅" "itR"
  , code "𝑆" "itS"
  , code "𝑇" "itT"
  , code "𝑈" "itU"
  , code "𝑉" "itV"
  , code "𝑊" "itW"
  , code "𝑋" "itX"
  , code "𝑌" "itY"
  , code "𝑍" "itZ"
  , code "𝑎" "ita"
  , code "𝑏" "itb"
  , code "𝑐" "itc"
  , code "𝑑" "itd"
  , code "𝑒" "ite"
  , code "𝑓" "itf"
  , code "𝑔" "itg"
  , code "ℎ" "ith"
  , code "𝑖" "iti"
  , code "𝑗" "itj"
  , code "𝑘" "itk"
  , code "𝑙" "itl"
  , code "𝑚" "itm"
  , code "𝑛" "itn"
  , code "𝑜" "ito"
  , code "𝑝" "itp"
  , code "𝑞" "itq"
  , code "𝑟" "itr"
  , code "𝑠" "its"
  , code "𝑡" "itt"
  , code "𝑢" "itu"
  , code "𝑣" "itv"
  , code "𝑤" "itw"
  , code "𝑥" "itx"
  , code "𝑦" "ity"
  , code "𝑧" "itz"

  -- Roman Bold Itallic
  , code "𝑨" "blditA"
  , code "𝑩" "blditB"
  , code "𝑪" "blditC"
  , code "𝑫" "blditD"
  , code "𝑬" "blditE"
  , code "𝑭" "blditF"
  , code "𝑮" "blditG"
  , code "𝑯" "blditH"
  , code "𝑰" "blditI"
  , code "𝑱" "blditJ"
  , code "𝑲" "blditK"
  , code "𝑳" "blditL"
  , code "𝑴" "blditM"
  , code "𝑵" "blditN"
  , code "𝑶" "blditO"
  , code "𝑷" "blditP"
  , code "𝑸" "blditQ"
  , code "𝑹" "blditR"
  , code "𝑺" "blditS"
  , code "𝑻" "blditT"
  , code "𝑼" "blditU"
  , code "𝑽" "blditV"
  , code "𝑾" "blditW"
  , code "𝑿" "blditX"
  , code "𝒀" "blditY"
  , code "𝒁" "blditZ"
  , code "𝒂" "bldita"
  , code "𝒃" "blditb"
  , code "𝒄" "blditc"
  , code "𝒅" "blditd"
  , code "𝒆" "bldite"
  , code "𝒇" "blditf"
  , code "𝒈" "blditg"
  , code "𝒉" "bldith"
  , code "𝒊" "blditi"
  , code "𝒋" "blditj"
  , code "𝒌" "blditk"
  , code "𝒍" "blditl"
  , code "𝒎" "blditm"
  , code "𝒏" "blditn"
  , code "𝒐" "bldito"
  , code "𝒑" "blditp"
  , code "𝒒" "blditq"
  , code "𝒓" "blditr"
  , code "𝒔" "bldits"
  , code "𝒕" "blditt"
  , code "𝒖" "blditu"
  , code "𝒗" "blditv"
  , code "𝒘" "blditw"
  , code "𝒙" "blditx"
  , code "𝒚" "bldity"
  , code "𝒛" "blditz"

  -- Roman Caligraphy
  , lcode "𝒜" "calA" "\\mathcal{A}"
  , lcode "ℬ" "calB" "\\mathcal{B}"
  , lcode "𝒞" "calC" "\\mathcal{C}"
  , lcode "𝒟" "calD" "\\mathcal{D}"
  , lcode "ℰ" "calE" "\\mathcal{E}"
  , lcode "ℱ" "calF" "\\mathcal{F}"
  , lcode "𝒢" "calG" "\\mathcal{G}"
  , lcode "ℋ" "calH" "\\mathcal{H}"
  , lcode "ℐ" "calI" "\\mathcal{I}"
  , lcode "𝒥" "calJ" "\\mathcal{J}"
  , lcode "𝒦" "calK" "\\mathcal{K}"
  , lcode "ℒ" "calL" "\\mathcal{L}"
  , lcode "ℳ" "calM" "\\mathcal{M}"
  , lcode "𝒩" "calN" "\\mathcal{N}"
  , lcode "𝒪" "calO" "\\mathcal{O}"
  , lcode "𝒫" "calP" "\\mathcal{P}"
  , lcode "𝒬" "calQ" "\\mathcal{Q}"
  , lcode "ℛ" "calR" "\\mathcal{R}"
  , lcode "𝒮" "calS" "\\mathcal{S}"
  , lcode "𝒯" "calT" "\\mathcal{T}"
  , lcode "𝒰" "calU" "\\mathcal{U}"
  , lcode "𝒱" "calV" "\\mathcal{V}"
  , lcode "𝒲" "calW" "\\mathcal{W}"
  , lcode "𝒳" "calX" "\\mathcal{X}"
  , lcode "𝒴" "calY" "\\mathcal{Y}"
  , lcode "𝒵" "calZ" "\\mathcal{Z}"
  , lcode "𝒶" "cala" "\\mathcal{a}"
  , lcode "𝒷" "calb" "\\mathcal{b}"
  , lcode "𝒸" "calc" "\\mathcal{c}"
  , lcode "𝒹" "cald" "\\mathcal{d}"
  , lcode "ℯ" "cale" "\\mathcal{e}"
  , lcode "𝒻" "calf" "\\mathcal{f}"
  , lcode "ℊ" "calg" "\\mathcal{g}"
  , lcode "𝒽" "calh" "\\mathcal{h}"
  , lcode "𝒾" "cali" "\\mathcal{i}"
  , lcode "𝒿" "calj" "\\mathcal{j}"
  , lcode "𝓀" "calk" "\\mathcal{k}"
  , lcode "𝓁" "call" "\\mathcal{l}"
  , lcode "𝓂" "calm" "\\mathcal{m}"
  , lcode "𝓃" "caln" "\\mathcal{n}"
  , lcode "ℴ" "calo" "\\mathcal{o}"
  , lcode "𝓅" "calp" "\\mathcal{p}"
  , lcode "𝓆" "calq" "\\mathcal{q}"
  , lcode "𝓇" "calr" "\\mathcal{r}"
  , lcode "𝓈" "cals" "\\mathcal{s}"
  , lcode "𝓉" "calt" "\\mathcal{t}"
  , lcode "𝓊" "calu" "\\mathcal{u}"
  , lcode "𝓋" "calv" "\\mathcal{v}"
  , lcode "𝓌" "calw" "\\mathcal{w}"
  , lcode "𝓍" "calx" "\\mathcal{x}"
  , lcode "𝓎" "caly" "\\mathcal{y}"
  , lcode "𝓏" "calz" "\\mathcal{z}"

  -- Roman Bold Caligraphy
  , code "𝓐" "bldcalA"
  , code "𝓑" "bldcalB"
  , code "𝓒" "bldcalC"
  , code "𝓓" "bldcalD"
  , code "𝓔" "bldcalE"
  , code "𝓕" "bldcalF"
  , code "𝓖" "bldcalG"
  , code "𝓗" "bldcalH"
  , code "𝓘" "bldcalI"
  , code "𝓙" "bldcalJ"
  , code "𝓚" "bldcalK"
  , code "𝓛" "bldcalL"
  , code "𝓜" "bldcalM"
  , code "𝓝" "bldcalN"
  , code "𝓞" "bldcalO"
  , code "𝓟" "bldcalP"
  , code "𝓠" "bldcalQ"
  , code "𝓡" "bldcalR"
  , code "𝓢" "bldcalS"
  , code "𝓣" "bldcalT"
  , code "𝓤" "bldcalU"
  , code "𝓥" "bldcalV"
  , code "𝓦" "bldcalW"
  , code "𝓧" "bldcalX"
  , code "𝓨" "bldcalY"
  , code "𝓩" "bldcalZ"
  , code "𝓪" "bldcala"
  , code "𝓫" "bldcalb"
  , code "𝓬" "bldcalc"
  , code "𝓭" "bldcald"
  , code "𝓮" "bldcale"
  , code "𝓯" "bldcalf"
  , code "𝓰" "bldcalg"
  , code "𝓱" "bldcalh"
  , code "𝓲" "bldcali"
  , code "𝓳" "bldcalj"
  , code "𝓴" "bldcalk"
  , code "𝓵" "bldcall"
  , code "𝓶" "bldcalm"
  , code "𝓷" "bldcaln"
  , code "𝓸" "bldcalo"
  , code "𝓹" "bldcalp"
  , code "𝓺" "bldcalq"
  , code "𝓻" "bldcalr"
  , code "𝓼" "bldcals"
  , code "𝓽" "bldcalt"
  , code "𝓾" "bldcalu"
  , code "𝓿" "bldcalv"
  , code "𝔀" "bldcalw"
  , code "𝔁" "bldcalx"
  , code "𝔂" "bldcaly"
  , code "𝔃" "bldcalz"

  -- Roman Fraktur
  , code "𝔄" "frakA"
  , code "𝔅" "frakB"
  , code "ℭ" "frakC"
  , code "𝔇" "frakD"
  , code "𝔈" "frakE"
  , code "𝔉" "frakF"
  , code "𝔊" "frakG"
  , code "ℌ" "frakH"
  , code "ℑ" "frakI"
  , code "𝔍" "frakJ"
  , code "𝔎" "frakK"
  , code "𝔏" "frakL"
  , code "𝔐" "frakM"
  , code "𝔑" "frakN"
  , code "𝔒" "frakO"
  , code "𝔓" "frakP"
  , code "𝔔" "frakQ"
  , code "ℜ" "frakR"
  , code "𝔖" "frakS"
  , code "𝔗" "frakT"
  , code "𝔘" "frakU"
  , code "𝔙" "frakV"
  , code "𝔚" "frakW"
  , code "𝔛" "frakX"
  , code "𝔜" "frakY"
  , code "ℨ" "frakZ"
  , code "𝔞" "fraka"
  , code "𝔟" "frakb"
  , code "𝔠" "frakc"
  , code "𝔡" "frakd"
  , code "𝔢" "frake"
  , code "𝔣" "frakf"
  , code "𝔤" "frakg"
  , code "𝔥" "frakh"
  , code "𝔦" "fraki"
  , code "𝔧" "frakj"
  , code "𝔨" "frakk"
  , code "𝔩" "frakl"
  , code "𝔪" "frakm"
  , code "𝔫" "frakn"
  , code "𝔬" "frako"
  , code "𝔭" "frakp"
  , code "𝔮" "frakq"
  , code "𝔯" "frakr"
  , code "𝔰" "fraks"
  , code "𝔱" "frakt"
  , code "𝔲" "fraku"
  , code "𝔳" "frakv"
  , code "𝔴" "frakw"
  , code "𝔵" "frakx"
  , code "𝔶" "fraky"
  , code "𝔷" "frakz"

  -- Roman Bold Fraktur
  , code "𝕬" "bldfrakA"
  , code "𝕭" "bldfrakB"
  , code "𝕮" "bldfrakC"
  , code "𝕯" "bldfrakD"
  , code "𝕰" "bldfrakE"
  , code "𝕱" "bldfrakF"
  , code "𝕲" "bldfrakG"
  , code "𝕳" "bldfrakH"
  , code "𝕴" "bldfrakI"
  , code "𝕵" "bldfrakJ"
  , code "𝕶" "bldfrakK"
  , code "𝕷" "bldfrakL"
  , code "𝕸" "bldfrakM"
  , code "𝕹" "bldfrakN"
  , code "𝕺" "bldfrakO"
  , code "𝕻" "bldfrakP"
  , code "𝕼" "bldfrakQ"
  , code "𝕽" "bldfrakR"
  , code "𝕾" "bldfrakS"
  , code "𝕿" "bldfrakT"
  , code "𝖀" "bldfrakU"
  , code "𝖁" "bldfrakV"
  , code "𝖂" "bldfrakW"
  , code "𝖃" "bldfrakX"
  , code "𝖄" "bldfrakY"
  , code "𝖅" "bldfrakZ"
  , code "𝖆" "bldfraka"
  , code "𝖇" "bldfrakb"
  , code "𝖈" "bldfrakc"
  , code "𝖉" "bldfrakd"
  , code "𝖊" "bldfrake"
  , code "𝖋" "bldfrakf"
  , code "𝖌" "bldfrakg"
  , code "𝖍" "bldfrakh"
  , code "𝖎" "bldfraki"
  , code "𝖏" "bldfrakj"
  , code "𝖐" "bldfrakk"
  , code "𝖑" "bldfrakl"
  , code "𝖒" "bldfrakm"
  , code "𝖓" "bldfrakn"
  , code "𝖔" "bldfrako"
  , code "𝖕" "bldfrakp"
  , code "𝖖" "bldfrakq"
  , code "𝖗" "bldfrakr"
  , code "𝖘" "bldfraks"
  , code "𝖙" "bldfrakt"
  , code "𝖚" "bldfraku"
  , code "𝖛" "bldfrakv"
  , code "𝖜" "bldfrakw"
  , code "𝖝" "bldfrakx"
  , code "𝖞" "bldfraky"
  , code "𝖟" "bldfrakz"

  -- Roman Blackboard Bold
  , lcode "𝔸" "bbA" "\\mathbb{A}"
  , lcode "𝔹" "bbB" "\\mathbb{B}"
  , lcode "ℂ" "bbC" "\\mathbb{C}"
  , lcode "𝔻" "bbD" "\\mathbb{D}"
  , lcode "𝔼" "bbE" "\\mathbb{E}"
  , lcode "𝔽" "bbF" "\\mathbb{F}"
  , lcode "𝔾" "bbG" "\\mathbb{G}"
  , lcode "ℍ" "bbH" "\\mathbb{H}"
  , lcode "𝕀" "bbI" "\\mathbb{I}"
  , lcode "𝕁" "bbJ" "\\mathbb{J}"
  , lcode "𝕂" "bbK" "\\mathbb{K}"
  , lcode "𝕃" "bbL" "\\mathbb{L}"
  , lcode "𝕄" "bbM" "\\mathbb{M}"
  , lcode "ℕ" "bbN" "\\mathbb{N}"
  , lcode "𝕆" "bbO" "\\mathbb{O}"
  , lcode "ℙ" "bbP" "\\mathbb{P}"
  , lcode "ℚ" "bbQ" "\\mathbb{Q}"
  , lcode "ℝ" "bbR" "\\mathbb{R}"
  , lcode "𝕊" "bbS" "\\mathbb{S}"
  , lcode "𝕋" "bbT" "\\mathbb{T}"
  , lcode "𝕌" "bbU" "\\mathbb{U}"
  , lcode "𝕍" "bbV" "\\mathbb{V}"
  , lcode "𝕎" "bbW" "\\mathbb{W}"
  , lcode "𝕏" "bbX" "\\mathbb{X}"
  , lcode "𝕐" "bbY" "\\mathbb{Y}"
  , lcode "ℤ" "bbZ" "\\mathbb{Z}"
  , lcode "𝕒" "bba" "\\mathbb{a}"
  , lcode "𝕓" "bbb" "\\mathbb{b}"
  , lcode "𝕔" "bbc" "\\mathbb{c}"
  , lcode "𝕕" "bbd" "\\mathbb{d}"
  , lcode "𝕖" "bbe" "\\mathbb{e}"
  , lcode "𝕗" "bbf" "\\mathbb{f}"
  , lcode "𝕘" "bbg" "\\mathbb{g}"
  , lcode "𝕙" "bbh" "\\mathbb{h}"
  , lcode "𝕚" "bbi" "\\mathbb{i}"
  , lcode "𝕛" "bbj" "\\mathbb{j}"
  , lcode "𝕜" "bbk" "\\mathbb{k}"
  , lcode "𝕝" "bbl" "\\mathbb{l}"
  , lcode "𝕞" "bbm" "\\mathbb{m}"
  , lcode "𝕟" "bbn" "\\mathbb{n}"
  , lcode "𝕠" "bbo" "\\mathbb{o}"
  , lcode "𝕡" "bbp" "\\mathbb{p}"
  , lcode "𝕢" "bbq" "\\mathbb{q}"
  , lcode "𝕣" "bbr" "\\mathbb{r}"
  , lcode "𝕤" "bbs" "\\mathbb{s}"
  , lcode "𝕥" "bbt" "\\mathbb{t}"
  , lcode "𝕦" "bbu" "\\mathbb{u}"
  , lcode "𝕧" "bbv" "\\mathbb{v}"
  , lcode "𝕨" "bbw" "\\mathbb{w}"
  , lcode "𝕩" "bbx" "\\mathbb{x}"
  , lcode "𝕪" "bby" "\\mathbb{y}"
  , lcode "𝕫" "bbz" "\\mathbb{z}"

  -- Roman Subscripts
  , lcode "ₐ" "_a" "_a"
  , lcode "ₑ" "_e" "_e"
  , lcode "ₕ" "_h" "_h"
  , lcode "ᵢ" "_i" "_i"
  , lcode "ⱼ" "_j" "_j"
  , lcode "ₖ" "_k" "_k"
  , lcode "ₗ" "_l" "_l"
  , lcode "ₘ" "_m" "_m"
  , lcode "ₙ" "_n" "_n"
  , lcode "ₒ" "_o" "_o"
  , lcode "ₚ" "_p" "_p"
  , lcode "ᵣ" "_r" "_r"
  , lcode "ₛ" "_s" "_s"
  , lcode "ₜ" "_t" "_t"
  , lcode "ᵤ" "_u" "_u"
  , lcode "ᵥ" "_v" "_v"
  , lcode "ₓ" "_x" "_x"

  -- Roman Superscripts
  , lcode "ᴬ" "^A" "^A"
  , lcode "ᴮ" "^B" "^B"
  , lcode "ᴰ" "^D" "^D"
  , lcode "ᴱ" "^E" "^E"
  , lcode "ᴳ" "^G" "^G"
  , lcode "ᴴ" "^H" "^H"
  , lcode "ᴵ" "^I" "^I"
  , lcode "ᴶ" "^J" "^J"
  , lcode "ᴷ" "^K" "^K"
  , lcode "ᴸ" "^L" "^L"
  , lcode "ᴹ" "^M" "^M"
  , lcode "ᴺ" "^N" "^N"
  , lcode "ᴼ" "^O" "^O"
  , lcode "ᴾ" "^P" "^P"
  , lcode "ᴿ" "^R" "^R"
  , lcode "ᵀ" "^T" "^T"
  , lcode "ᵁ" "^U" "^U"
  , lcode "ⱽ" "^V" "^V"
  , lcode "ᵂ" "^W" "^W"
  , lcode "ᵃ" "^a" "^a"
  , lcode "ᵇ" "^b" "^b"
  , lcode "ᶜ" "^c" "^c"
  , lcode "ᵈ" "^d" "^d"
  , lcode "ᵉ" "^e" "^e"
  , lcode "ᶠ" "^f" "^f"
  , lcode "ᵍ" "^g" "^g"
  , lcode "ʰ" "^h" "^h"
  , lcode "ⁱ" "^i" "^i"
  , lcode "ʲ" "^j" "^j"
  , lcode "ᵏ" "^k" "^k"
  , lcode "ˡ" "^l" "^l"
  , lcode "ᵐ" "^m" "^m"
  , lcode "ⁿ" "^n" "^n"
  , lcode "ᵒ" "^o" "^o"
  , lcode "ᵖ" "^p" "^p"
  , lcode "ʳ" "^r" "^r"
  , lcode "ˢ" "^s" "^s"
  , lcode "ᵗ" "^t" "^t"
  , lcode "ᵘ" "^u" "^u"
  , lcode "ᵛ" "^v" "^v"
  , lcode "ʷ" "^w" "^w"
  , lcode "ˣ" "^x" "^x"
  , lcode "ʸ" "^y" "^y"
  , lcode "ᶻ" "^z" "^z"

  -- Roman Small Upper Case
  , code "ᴀ" "smallA"
  , code "ʙ" "smallB"
  , code "ᴄ" "smallC"
  , code "ᴅ" "smallD"
  , code "ᴇ" "smallE"
  , code "ꜰ" "smallF"
  , code "ɢ" "smallG"
  , code "ʜ" "smallH"
  , code "ɪ" "smallI"
  , code "ᴊ" "smallJ"
  , code "ᴋ" "smallK"
  , code "ʟ" "smallL"
  , code "ᴍ" "smallM"
  , code "ɴ" "smallN"
  , code "ᴏ" "smallO"
  , code "ᴘ" "smallP"
  , code "ʀ" "smallR"
  , code "ꜱ" "smallS"
  , code "ᴛ" "smallT"
  , code "ᴜ" "smallU"
  , code "ᴠ" "smallV"
  , code "ᴡ" "smallW"
  , code "ʏ" "smallY"
  , code "ᴢ" "smallZ"

  -- Roman Accents and Gylphs
  , code "é" "e'"
  , code "è" "e`"
  , lcode "ö" "o.." "\\\"o"
  , code "æ" "ae"
  ]
