module UnicodeGen where

import Data.List

type UnicodeRep = String
type EscapeCode = String
type LatexRep = String
type Description = String

main :: IO ()
main = do
  writeFile "unicode.el" genEmacsScript
  writeFile "unicode.vim" genVimScript

data Code = Code UnicodeRep EscapeCode LatexRep Description

code :: UnicodeRep -> EscapeCode -> Code
code u e = Code u e "" ""

vimEscape :: String -> String
vimEscape = concatMap escapeChar
  where
    escapeChar :: Char -> String
    escapeChar '|' = "\\|"
    escapeChar c = [c]

emacsEscape :: String -> String
emacsEscape = concatMap escapeChar
  where
    escapeChar :: Char -> String
    escapeChar '\\' = "\\\\"
    escapeChar '\"' = "\\\""
    escapeChar c = [c]

genVimScript :: String
genVimScript = do
  code <- codes
  command code
  where
    command :: Code -> String
    command (Code u e _ _) = "noremap! " ++ vimEscape ("\\" ++ e) ++ " " ++ vimEscape u ++ "\n"

genEmacsScript :: String
genEmacsScript = concat $ intersperse "\n"
  [ "(quail-define-package"
  , " \"darais\""
  , " \"UTF-32\""
  , " \"DaraisInput\""
  , " t"
  , " \"David Darais's personal input codes\""
  , " nil t nil nil nil nil nil nil nil nil t)"
  , "(quail-define-rules"
  , do
      code <- codes
      command code
    ++ ")"
  ]
  where
      command :: Code -> String
      command (Code u e _ _) = " (\"" ++ emacsEscape ("\\" ++ e) ++ "\" \"" ++ emacsEscape u ++ "\")" ++ "\n"

codes :: [Code]
codes = 
  -- Backslash
  [ code "\\"  "\\"

  -- Arrows
  , code "→"   "->"
  , code "←"   "<-"
  , code "↑"   "u"
  , code "↓"   "d"
  , code "↗"   "ur"
  , code "↘"   "dr"
  , code "↔"   "<->"
  , code "⇄"   "iso"
  , code "⇉"   "->->"
  , code "⇒"   "=>"
  , code "⇐"   "=<"
  , code "⇑"   "=u"
  , code "⇓"   "=d"
  , code "⇨"   "|=>"
  , code "⇦"   "|=<"
  , code "⇧"   "|=u"
  , code "⇩"   "|=d"
  , code "⇔"   "<=>"
  , code "⇰"   "||=>"
  , code "⇀"   "-\\"
  , code "↦"   "|->"
  , code "⇥"   "->|"
  , code "⇤"   "|<-"
  , code "↠"   "->>"
  , code "⇾"   "-|>"
  , code "⇿"   "<|-|>"
  , code "↝"   "~>"
  , code "↜"   "~<"
  , code "⇝"   "~~>"
  , code "↯"   "zd"

  -- Brackets
  , code "⟨"   "<"
  , code "⟩"   ">"
  , code "⟪"   "<<"
  , code "⟫"   ">>"
  , code "⦉"   "|<"
  , code "⦊"   "|>"
  , code "⦑"   ".<"
  , code "⦒"   ".>"
  , code "«"   "\"<"
  , code "»"   "\">"
  , code "⟮"   "("
  , code "⟯"   ")"
  , code "⸨"   "(("
  , code "⸩"   "))"
  , code "⦇"   "|("
  , code "⦈"   "|)"
  , code "⦅"   "c("
  , code "⦆"   "c)"
  , code "⟦"   "[["
  , code "⟧"   "]]"
  , code "⟬"   "|["
  , code "⟭"   "|]"
  , code "⌈"   "tL"
  , code "⌉"   "tR"
  , code "⌊"   "bL"
  , code "⌋"   "bR"
  , code "⸢"   "tl"
  , code "⸣"   "tr"
  , code "⸤"   "bl"
  , code "⸥"   "br"
  , code "⦃"   "{{"
  , code "⦄"   "}}"
  , code "⧘"   "z{"
  , code "⧙"   "z}"
  , code "⧚"   "zz{"
  , code "⧛"   "zz}"
  , code "⟅"   "s{"
  , code "⟆"   "s}"

  -- Quotes
  , code "“" "``"
  , code "”" "''"
  , code "—" "--"

  -- Operators
  , code "⋅" "." 
  , code "∶" ":"
  , code "∵" ".:"
  , code "∷" "::"
  , code "…" "..."
  , code "∘" "o"
  , code "⊙" "o."
  , code "⌾" "oo"
  , code "⦂" "o:"
  , code "⨟" "o;"
  , code "¦" "|:"
  , code "‖" "||"
  , code "∅" "O/"
  , code "⋆" "*"
  , code "★" "star"
  , code "♯" "#"
  , code "𝄪" "##"
  , code "♭" "b"
  , code "♮" "n"
  , code "⋕" "=||"
  , code "⁇" "??"
  , code "⧺" "++"
  , code "×" "x"
  , code "⨯" "xx"
  , code "⤨" "swap"
  , code "⊕" "o+"
  , code "⊖" "o-"
  , code "⊗" "ox"
  , code "⧀" "o<"
  , code "⎊" "ot"
  , code "◇" "d"
  , code "⟐" "d."
  , code "□" "s"
  , code "⊞" "s+"
  , code "⊟" "s-"
  , code "⊠" "sx"
  , code "⊡" "s."
  , code "∎" "qed"
  , code "⌿" "-/"
 
  -- Logic
  , code "∈" "in"
  , code "⋵" "in."
  , code "∉" "in/"
  , code "∋" "co"
  , code "⋿" "mem"
  , code "∀" "all"
  , code "∃" "ex"
  , code "⊢" "|-"
  , code "⊨" "|="
  , code "∨" "or"
  , code "∧" "and"
  , code "⋎" "sor"
  , code "⋏" "sand"
  , code "⊥" "bot"
  , code "⊤" "top"
  , code "¬" "neg"
 
  -- Orders
  , code "⊆" "s<="
  , code "⊇" "s>="
  , code "∪" "u"
  , code "∩" "i"
  , code "⊍" "u."
  , code "⨄" "u+"
  , code "⋃" "U"
  , code "⋂" "I"
  , code "≤" "<="
  , code "≥" ">="
  , code "⋚" "<=>="
  , code "⊑" "p<="
  , code "⊒" "p>="
  , code "⊏" "p<"
  , code "⊐" "p>"
  , code "⋤" "p<=/"
  , code "⊔" "j"
  , code "⊓" "m"
  , code "⨆" "J"
  , code "⋈" "bow"
  , code "∞" "inf"
  , code "≺" "c<"
  , code "≻" "c>"
  , code "≼" "c<="
  , code "≽" "c>="
  , code "⊴" "t<="
  , code "⊵" "t>="
  , code "⋬" "t<=/"
  , code "⋭" "t>=/"
  , code "⩻" "<?"
  , code "⩼" ">?"
  , code "⧼" "y<"
  , code "⧽" "y>"
  , code "‹" "<1"
  , code "›" ">1"
  , code "≪" "<2"
  , code "≫" ">2"
  , code "≫=" ">>="
  , code "≪=" "<<="
 
  -- Equality
  , code "≡" "=="
  , code "≃" "~="
  , code "≈" "~~"
  , code "≔" ":="
  , code "⩴" "::="
  , code "≠" "=/"
  , code "≢" "==/"
  , code "≟" "=?"
  , code "≜" "=t"
 
  -- Subscripts
  , code "₊" "_+"
  , code "₋" "_-"
  , code "₍" "_("
  , code "₎" "_)"
  
  -- Superscripts
  , code "⁺" "^+"
  , code "⁻" "^-"
  , code "⁽" "^("
  , code "⁾" "^)"
  , code "˚" "^^o"

  -- Markup
  , code "¶" "PP"
  , code "␣" "_"
  , code "§" "SS"
 
  -- Bullets
  , code "•" "bu"
  , code "◦" "buw"
  , code "⁃" "buh"
  , code "‣" "but"
 
  -- Triangles
  , code "◁" "trl"
  , code "△" "tru"
  , code "▷" "trr"
  , code "▽" "trd"
 
  -- OK
  , code "✓" "yes"
  , code "✗" "no"

  -- Greek Normal
  , code "Α"  "Alpha"
  , code "Β"  "Beta"
  , code "Γ"  "Gamma"
  , code "Δ"  "Delta"
  , code "Ε"  "Epsilon"
  , code "Ζ"  "Zeta"
  , code "Η"  "Eta"
  , code "Θ"  "Theta"
  , code "Ι"  "Iota"
  , code "Κ"  "Kappa"
  , code "Λ"  "Lambda"
  , code "Μ"  "Mu"
  , code "Ν"  "Nu"
  , code "Ξ"  "Xi"
  , code "Ο"  "Omicron"
  , code "Π"  "Pi"
  , code "Ρ"  "Rho"
  , code "ϴ"  "varSigma"
  , code "Σ"  "Sigma"
  , code "Τ"  "Tau"
  , code "Υ"  "Upsilon"
  , code "Φ"  "Phi"
  , code "Χ"  "Chi"
  , code "Ψ"  "Psi"
  , code "Ω"  "Omega"
  , code "∇"  "Nabla"
                                       
  , code "α"   "alpha"
  , code "β"   "beta"
  , code "γ"   "gamma"
  , code "δ"   "delta"
  , code "ε"   "epsilon"
  , code "ζ"   "zeta"
  , code "η"   "eta"
  , code "θ"   "theta"
  , code "ι"   "iota"
  , code "κ"   "kappa"
  , code "λ"   "lambda"
  , code "μ"   "mu"
  , code "ν"   "nu"
  , code "ξ"   "xi"
  , code "ο"   "omicron"
  , code "π"   "pi"
  , code "ρ"   "rho"
  , code "ς"   "varsigma"
  , code "σ"   "sigma"
  , code "τ"   "tau"
  , code "υ"   "upsilon"
  , code "φ"   "phi"
  , code "χ"   "chi"
  , code "ψ"   "psi"
  , code "ω"   "omega"
  , code "∂"   "nabla"
                                       
  , code "ϵ"  "varepsilon"
  , code "ϑ"  "vartheta"
  , code "ϰ"  "varkappa"
  , code "ϕ"  "varphi"
  , code "ϱ"  "varrho"
  , code "ϖ"  "varpi"

  -- Greek Bold
  , code "𝚨"     "bldAlpha"
  , code "𝚩"     "bldBeta"
  , code "𝚪"     "bldGamma"
  , code "𝚫"     "bldDelta"
  , code "𝚬"     "bldEpsilon"
  , code "𝚭"     "bldZeta"
  , code "𝚮"     "bldEta"
  , code "𝚯"     "bldTheta"
  , code "𝚰"     "bldIota"
  , code "𝚱"     "bldKappa"
  , code "𝚲"     "bldLambda"
  , code "𝚳"     "bldMu"
  , code "𝚴"     "bldNu"
  , code "𝚵"     "bldXi"
  , code "𝚶"     "bldOmicron"
  , code "𝚷"     "bldPi"
  , code "𝚸"     "bldRho"
  , code "𝚹"     "bldvarSigma"
  , code "𝚺"     "bldSigma"
  , code "𝚻"     "bldTau"
  , code "𝚼"     "bldUpsilon"
  , code "𝚽"     "bldPhi"
  , code "𝚾"     "bldChi"
  , code "𝚿"     "bldPsi"
  , code "𝛀"     "bldOmega"
  , code "𝛁"     "bldNabla"

  , code "𝛂"     "bldalpha"
  , code "𝛃"     "bldbeta"
  , code "𝛄"     "bldgamma"
  , code "𝛅"     "blddelta"
  , code "𝛆"     "bldepsilon"
  , code "𝛇"     "bldzeta"
  , code "𝛈"     "bldldeta"
  , code "𝛉"     "bldtheta"
  , code "𝛊"     "bldiota"
  , code "𝛋"     "bldkappa"
  , code "𝛌"     "bldlambda"
  , code "𝛍"     "bldmu"
  , code "𝛎"     "bldnu"
  , code "𝛏"     "bldxi"
  , code "𝛐"     "bldomicron"
  , code "𝛑"     "bldpi"
  , code "𝛒"     "bldrho"
  , code "𝛓"     "bldvarsigma"
  , code "𝛔"     "bldsigma"
  , code "𝛕"     "bldtau"
  , code "𝛖"     "bldupsilon"
  , code "𝛗"     "bldphi"
  , code "𝛘"     "bldchi"
  , code "𝛙"     "bldpsi"
  , code "𝛚"     "bldomega"
  , code "𝛛"     "bldnabla"

  , code "𝛜"     "bvarepsilon"
  , code "𝛝"     "bvartheta"
  , code "𝛞"     "bvarkappa"
  , code "𝛟"     "bvarphi"
  , code "𝛠"     "bvarrho"
  , code "𝛡"     "bvarpi"

  -- Greek Italic
  , code "𝛢"    "itAlpha"
  , code "𝛣"    "itBeta"
  , code "𝛤"    "itGamma"
  , code "𝛥"    "itDelta"
  , code "𝛦"    "itEpsilon"
  , code "𝛧"    "itZeta"
  , code "𝛨"    "itEta"
  , code "𝛩"    "itTheta"
  , code "𝛪"    "itIota"
  , code "𝛫"    "itKappa"
  , code "𝛬"    "itLambda"
  , code "𝛭"    "itMu"
  , code "𝛮"    "itNu"
  , code "𝛯"    "itXi"
  , code "𝛰"    "itOmicron"
  , code "𝛱"    "itPi"
  , code "𝛲"    "itRho"
  , code "𝛳"    "itvarSigma"
  , code "𝛴"    "itSigma"
  , code "𝛵"    "itTau"
  , code "𝛶"    "itUpsilon"
  , code "𝛷"    "itPhi"
  , code "𝛸"    "itChi"
  , code "𝛹"    "itPsi"
  , code "𝛺"    "itOmega"
  , code "𝛻"    "itNabla"

  , code "𝛼"    "italpha"
  , code "𝛽"    "itbeta"
  , code "𝛾"    "itgamma"
  , code "𝛿"    "itdelta"
  , code "𝜀"    "itepsilon"
  , code "𝜁"    "itzeta"
  , code "𝜂"    "iteta"
  , code "𝜃"    "ittheta"
  , code "𝜄"    "itiota"
  , code "𝜅"    "itkappa"
  , code "𝜆"    "itlambda"
  , code "𝜇"    "itmu"
  , code "𝜈"    "itnu"
  , code "𝜉"    "itxi"
  , code "𝜊"    "itomicron"
  , code "𝜋"    "itpi"
  , code "𝜌"    "itrho"
  , code "𝜍"    "itvarsigma"
  , code "𝜎"    "itsigma"
  , code "𝜏"    "ittau"
  , code "𝜐"    "itupsilon"
  , code "𝜑"    "itphi"
  , code "𝜒"    "itchi"
  , code "𝜓"    "itpsi"
  , code "𝜔"    "itomega"
  , code "𝜕"    "itnabla"

  , code "𝜖"   "itvarepsilon"
  , code "𝜗"   "itvartheta"
  , code "𝜘"   "itvarkappa"
  , code "𝜙"   "itvarphi"
  , code "𝜚"   "itvarrho"
  , code "𝜛"   "itvarpi"

  -- Greek Bold Italic
  , code "𝜜"    "blditAlpha"
  , code "𝜝"    "blditBeta"
  , code "𝜞"    "blditGamma"
  , code "𝜟"    "blditDelta"
  , code "𝜠"    "blditEpsilon"
  , code "𝜡"    "blditZeta"
  , code "𝜢"    "blditEta"
  , code "𝜣"    "blditTheta"
  , code "𝜤"    "blditIota"
  , code "𝜥"    "blditKappa"
  , code "𝜦"    "blditLambda"
  , code "𝜧"    "blditMu"
  , code "𝜨"    "blditNu"
  , code "𝜩"    "blditXi"
  , code "𝜪"    "blditOmicron"
  , code "𝜫"    "blditPi"
  , code "𝜬"    "blditRho"
  , code "𝜭"    "blditvarSigma"
  , code "𝜮"    "blditSigma"
  , code "𝜯"    "blditTau"
  , code "𝜰"    "blditUpsilon"
  , code "𝜱"    "blditPhi"
  , code "𝜲"    "blditChi"
  , code "𝜳"    "blditPsi"
  , code "𝜴"    "blditOmega"
  , code "𝜵"    "blditNabla"

  , code "𝜶"    "blditalpha"
  , code "𝜷"    "blditbeta"
  , code "𝜸"    "blditgamma"
  , code "𝜹"    "blditdelta"
  , code "𝜺"    "blditepsilon"
  , code "𝜻"    "blditzeta"
  , code "𝜼"    "blditeta"
  , code "𝜽"    "bldittheta"
  , code "𝜾"    "blditiota"
  , code "𝜿"    "blditkappa"
  , code "𝝀"    "blditlambda"
  , code "𝝁"    "blditmu"
  , code "𝝂"    "blditnu"
  , code "𝝃"    "blditxi"
  , code "𝝄"    "blditomicron"
  , code "𝝅"    "blditpi"
  , code "𝝆"    "blditrho"
  , code "𝝇"    "blditvarsigma"
  , code "𝝈"    "blditsigma"
  , code "𝝉"    "bldittau"
  , code "𝝊"    "blditupsilon"
  , code "𝝋"    "blditphi"
  , code "𝝌"    "blditchi"
  , code "𝝍"    "blditpsi"
  , code "𝝎"    "blditomega"
  , code "𝝏"    "blditnabla"

  , code "𝝐"    "blditeepsilon"
  , code "𝝑"    "blditttheta"
  , code "𝝒"    "blditkkappa"
  , code "𝝓"    "blditpphi"
  , code "𝝔"    "blditrrho"
  , code "𝝕"    "blditppi"

  -- Greek Subscript
  , code "ᵦ"  "_beta"
  , code "ᵧ"  "_gamma"
  , code "ᵨ"  "_rho"
  , code "ᵩ"  "_phi"
  , code "ᵪ"  "_chi"

  -- Greek Superscript
  , code "ᵅ"   "^alpha"
  , code "ᵝ"   "^beta"
  , code "ᵞ"   "^gamma"
  , code "ᵟ"   "^delta"
  , code "ᵋ"   "^epsilon"
  , code "ᶿ"   "^theta"
  , code "ᶥ"   "^iota"
  , code "ᶲ"   "^Phi"
  , code "ᵠ"   "^phi"
  , code "ᵡ"   "^chi"

  -- Greek Blackboard Bold
  , code "ℾ"   "bbGamma"
  , code "ℽ"   "bbgamma"
  , code "ℿ"   "bbPi"
  , code "ℼ"   "bbpi"
  , code "⅀"   "bbSigma"

  -- Numbers Bold
  , code "𝟎" "bld0"
  , code "𝟏" "bld1"
  , code "𝟐" "bld2"
  , code "𝟑" "bld3"
  , code "𝟒" "bld4"
  , code "𝟓" "bld5"
  , code "𝟔" "bld6"
  , code "𝟕" "bld7"
  , code "𝟖" "bld8"
  , code "𝟗" "bld9"

  -- Numbers Blackboard Bold
  , code "𝟘" "bb0"
  , code "𝟙" "bb1"
  , code "𝟚" "bb2"
  , code "𝟛" "bb3"
  , code "𝟜" "bb4"
  , code "𝟝" "bb5"
  , code "𝟞" "bb6"
  , code "𝟟" "bb7"
  , code "𝟠" "bb8"
  , code "𝟡" "bb9"

  -- Numbers Subscript
  , code "₀" "_0"    
  , code "₁" "_1"    
  , code "₂" "_2"    
  , code "₃" "_3"    
  , code "₄" "_4"    
  , code "₅" "_5"    
  , code "₆" "_6"    
  , code "₇" "_7"    
  , code "₈" "_8"    
  , code "₉" "_9"    

  -- Numbers Superscript
  , code "⁰" "^0"      
  , code "¹" "^1"      
  , code "²" "^2"      
  , code "³" "^3"      
  , code "⁴" "^4"      
  , code "⁵" "^5"      
  , code "⁶" "^6"      
  , code "⁷" "^7"      
  , code "⁸" "^8"      
  , code "⁹" "^9"      

  --  Weierstrass p
  , code "℘" "wp"      

  -- Roman Bold
  , code "𝐀" "bldA"            
  , code "𝐁" "bldB"            
  , code "𝐂" "bldC"            
  , code "𝐃" "bldD"            
  , code "𝐄" "bldE"            
  , code "𝐅" "bldF"            
  , code "𝐆" "bldG"            
  , code "𝐇" "bldH"            
  , code "𝐈" "bldI"            
  , code "𝐉" "bldJ"            
  , code "𝐊" "bldK"            
  , code "𝐋" "bldL"            
  , code "𝐌" "bldM"            
  , code "𝐍" "bldN"            
  , code "𝐎" "bldO"            
  , code "𝐏" "bldP"            
  , code "𝐐" "bldQ"            
  , code "𝐑" "bldR"            
  , code "𝐒" "bldS"            
  , code "𝐓" "bldT"            
  , code "𝐔" "bldU"            
  , code "𝐕" "bldV"            
  , code "𝐖" "bldW"            
  , code "𝐗" "bldX"            
  , code "𝐘" "bldY"            
  , code "𝐙" "bldZ"            
  , code "𝐚" "blda"            
  , code "𝐛" "bldb"            
  , code "𝐜" "bldc"            
  , code "𝐝" "bldd"            
  , code "𝐞" "blde"            
  , code "𝐟" "bldf"            
  , code "𝐠" "bldg"            
  , code "𝐡" "bldh"            
  , code "𝐢" "bldi"            
  , code "𝐣" "bldj"            
  , code "𝐤" "bldk"            
  , code "𝐥" "bldl"            
  , code "𝐦" "bldm"            
  , code "𝐧" "bldn"            
  , code "𝐨" "bldo"            
  , code "𝐩" "bldp"            
  , code "𝐪" "bldq"            
  , code "𝐫" "bldr"            
  , code "𝐬" "blds"            
  , code "𝐭" "bldt"            
  , code "𝐮" "bldu"            
  , code "𝐯" "bldv"            
  , code "𝐰" "bldw"            
  , code "𝐱" "bldx"            
  , code "𝐲" "bldy"            
  , code "𝐳" "bldz"            

  -- Roman Itallic
  , code "𝐴" "itA"            
  , code "𝐵" "itB"            
  , code "𝐶" "itC"            
  , code "𝐷" "itD"            
  , code "𝐸" "itE"            
  , code "𝐹" "itF"            
  , code "𝐺" "itG"            
  , code "𝐻" "itH"            
  , code "𝐼" "itI"            
  , code "𝐽" "itJ"            
  , code "𝐾" "itK"            
  , code "𝐿" "itL"            
  , code "𝑀" "itM"            
  , code "𝑁" "itN"            
  , code "𝑂" "itO"            
  , code "𝑃" "itP"            
  , code "𝑄" "itQ"            
  , code "𝑅" "itR"            
  , code "𝑆" "itS"            
  , code "𝑇" "itT"            
  , code "𝑈" "itU"            
  , code "𝑉" "itV"            
  , code "𝑊" "itW"            
  , code "𝑋" "itX"            
  , code "𝑌" "itY"            
  , code "𝑍" "itZ"            
  , code "𝑎" "ita"            
  , code "𝑏" "itb"            
  , code "𝑐" "itc"            
  , code "𝑑" "itd"            
  , code "𝑒" "ite"            
  , code "𝑓" "itf"            
  , code "𝑔" "itg"            
  , code "ℎ" "ith"            
  , code "𝑖" "iti"            
  , code "𝑗" "itj"            
  , code "𝑘" "itk"            
  , code "𝑙" "itl"            
  , code "𝑚" "itm"            
  , code "𝑛" "itn"            
  , code "𝑜" "ito"            
  , code "𝑝" "itp"            
  , code "𝑞" "itq"            
  , code "𝑟" "itr"            
  , code "𝑠" "its"            
  , code "𝑡" "itt"            
  , code "𝑢" "itu"            
  , code "𝑣" "itv"            
  , code "𝑤" "itw"            
  , code "𝑥" "itx"            
  , code "𝑦" "ity"            
  , code "𝑧" "itz"            

  -- Roman Bold Itallic
  , code "𝑨" "blditA"           
  , code "𝑩" "blditB"           
  , code "𝑪" "blditC"           
  , code "𝑫" "blditD"           
  , code "𝑬" "blditE"           
  , code "𝑭" "blditF"           
  , code "𝑮" "blditG"           
  , code "𝑯" "blditH"           
  , code "𝑰" "blditI"           
  , code "𝑱" "blditJ"           
  , code "𝑲" "blditK"           
  , code "𝑳" "blditL"           
  , code "𝑴" "blditM"           
  , code "𝑵" "blditN"           
  , code "𝑶" "blditO"           
  , code "𝑷" "blditP"           
  , code "𝑸" "blditQ"           
  , code "𝑹" "blditR"           
  , code "𝑺" "blditS"           
  , code "𝑻" "blditT"           
  , code "𝑼" "blditU"           
  , code "𝑽" "blditV"           
  , code "𝑾" "blditW"           
  , code "𝑿" "blditX"           
  , code "𝒀" "blditY"           
  , code "𝒁" "blditZ"           
  , code "𝒂" "bldita"           
  , code "𝒃" "blditb"           
  , code "𝒄" "blditc"           
  , code "𝒅" "blditd"           
  , code "𝒆" "bldite"           
  , code "𝒇" "blditf"           
  , code "𝒈" "blditg"           
  , code "𝒉" "bldith"           
  , code "𝒊" "blditi"           
  , code "𝒋" "blditj"           
  , code "𝒌" "blditk"           
  , code "𝒍" "blditl"           
  , code "𝒎" "blditm"           
  , code "𝒏" "blditn"           
  , code "𝒐" "bldito"           
  , code "𝒑" "blditp"           
  , code "𝒒" "blditq"           
  , code "𝒓" "blditr"           
  , code "𝒔" "bldits"           
  , code "𝒕" "blditt"           
  , code "𝒖" "blditu"           
  , code "𝒗" "blditv"           
  , code "𝒘" "blditw"           
  , code "𝒙" "blditx"           
  , code "𝒚" "bldity"           
  , code "𝒛" "blditz"           

  -- Roman Caligraphy
  , code "𝒜" "calA"            
  , code "ℬ" "calB"            
  , code "𝒞" "calC"            
  , code "𝒟" "calD"            
  , code "ℰ" "calE"            
  , code "ℱ" "calF"            
  , code "𝒢" "calG"            
  , code "ℋ" "calH"            
  , code "ℐ" "calI"            
  , code "𝒥" "calJ"            
  , code "𝒦" "calK"            
  , code "ℒ" "calL"            
  , code "ℳ" "calM"            
  , code "𝒩" "calN"            
  , code "𝒪" "calO"            
  , code "𝒫" "calP"            
  , code "𝒬" "calQ"            
  , code "ℛ" "calR"            
  , code "𝒮" "calS"            
  , code "𝒯" "calT"            
  , code "𝒰" "calU"            
  , code "𝒱" "calV"            
  , code "𝒲" "calW"            
  , code "𝒳" "calX"            
  , code "𝒴" "calY"            
  , code "𝒵" "calZ"            
  , code "𝒶" "cala"            
  , code "𝒷" "calb"            
  , code "𝒸" "calc"            
  , code "𝒹" "cald"            
  , code "ℯ" "cale"            
  , code "𝒻" "calf"            
  , code "ℊ" "calg"            
  , code "𝒽" "calh"            
  , code "𝒾" "cali"            
  , code "𝒿" "calj"            
  , code "𝓀" "calk"            
  , code "𝓁" "call"            
  , code "𝓂" "calm"            
  , code "𝓃" "caln"            
  , code "ℴ" "calo"            
  , code "𝓅" "calp"            
  , code "𝓆" "calq"            
  , code "𝓇" "calr"            
  , code "𝓈" "cals"            
  , code "𝓉" "calt"            
  , code "𝓊" "calu"            
  , code "𝓋" "calv"            
  , code "𝓌" "calw"            
  , code "𝓍" "calx"            
  , code "𝓎" "caly"            
  , code "𝓏" "calz"            

  -- Roman Bold Caligraphy
  , code "𝓐" "bldcalA"           
  , code "𝓑" "bldcalB"           
  , code "𝓒" "bldcalC"           
  , code "𝓓" "bldcalD"           
  , code "𝓔" "bldcalE"           
  , code "𝓕" "bldcalF"           
  , code "𝓖" "bldcalG"           
  , code "𝓗" "bldcalH"           
  , code "𝓘" "bldcalI"           
  , code "𝓙" "bldcalJ"           
  , code "𝓚" "bldcalK"           
  , code "𝓛" "bldcalL"           
  , code "𝓜" "bldcalM"           
  , code "𝓝" "bldcalN"           
  , code "𝓞" "bldcalO"           
  , code "𝓟" "bldcalP"           
  , code "𝓠" "bldcalQ"           
  , code "𝓡" "bldcalR"           
  , code "𝓢" "bldcalS"           
  , code "𝓣" "bldcalT"           
  , code "𝓤" "bldcalU"           
  , code "𝓥" "bldcalV"           
  , code "𝓦" "bldcalW"           
  , code "𝓧" "bldcalX"           
  , code "𝓨" "bldcalY"           
  , code "𝓩" "bldcalZ"           
  , code "𝓪" "bldcala"           
  , code "𝓫" "bldcalb"           
  , code "𝓬" "bldcalc"           
  , code "𝓭" "bldcald"           
  , code "𝓮" "bldcale"           
  , code "𝓯" "bldcalf"           
  , code "𝓰" "bldcalg"           
  , code "𝓱" "bldcalh"           
  , code "𝓲" "bldcali"           
  , code "𝓳" "bldcalj"           
  , code "𝓴" "bldcalk"           
  , code "𝓵" "bldcall"           
  , code "𝓶" "bldcalm"           
  , code "𝓷" "bldcaln"           
  , code "𝓸" "bldcalo"           
  , code "𝓹" "bldcalp"           
  , code "𝓺" "bldcalq"           
  , code "𝓻" "bldcalr"           
  , code "𝓼" "bldcals"           
  , code "𝓽" "bldcalt"           
  , code "𝓾" "bldcalu"           
  , code "𝓿" "bldcalv"           
  , code "𝔀" "bldcalw"           
  , code "𝔁" "bldcalx"           
  , code "𝔂" "bldcaly"           
  , code "𝔃" "bldcalz"           

  -- Roman Fraktur
  , code "𝔄" "frakA"            
  , code "𝔅" "frakB"            
  , code "ℭ" "frakC"            
  , code "𝔇" "frakD"            
  , code "𝔈" "frakE"            
  , code "𝔉" "frakF"            
  , code "𝔊" "frakG"            
  , code "ℌ" "frakH"            
  , code "ℑ" "frakI"            
  , code "𝔍" "frakJ"            
  , code "𝔎" "frakK"            
  , code "𝔏" "frakL"            
  , code "𝔐" "frakM"            
  , code "𝔑" "frakN"            
  , code "𝔒" "frakO"            
  , code "𝔓" "frakP"            
  , code "𝔔" "frakQ"            
  , code "ℜ" "frakR"            
  , code "𝔖" "frakS"            
  , code "𝔗" "frakT"            
  , code "𝔘" "frakU"            
  , code "𝔙" "frakV"            
  , code "𝔚" "frakW"            
  , code "𝔛" "frakX"            
  , code "𝔜" "frakY"            
  , code "ℨ" "frakZ"            
  , code "𝔞" "fraka"            
  , code "𝔟" "frakb"            
  , code "𝔠" "frakc"            
  , code "𝔡" "frakd"            
  , code "𝔢" "frake"            
  , code "𝔣" "frakf"            
  , code "𝔤" "frakg"            
  , code "𝔥" "frakh"            
  , code "𝔦" "fraki"            
  , code "𝔧" "frakj"            
  , code "𝔨" "frakk"            
  , code "𝔩" "frakl"            
  , code "𝔪" "frakm"            
  , code "𝔫" "frakn"            
  , code "𝔬" "frako"            
  , code "𝔭" "frakp"            
  , code "𝔮" "frakq"            
  , code "𝔯" "frakr"            
  , code "𝔰" "fraks"            
  , code "𝔱" "frakt"            
  , code "𝔲" "fraku"            
  , code "𝔳" "frakv"            
  , code "𝔴" "frakw"            
  , code "𝔵" "frakx"            
  , code "𝔶" "fraky"            
  , code "𝔷" "frakz"            

  -- Roman Bold Fraktur
  , code "𝕬" "bldfrakA"           
  , code "𝕭" "bldfrakB"           
  , code "𝕮" "bldfrakC"           
  , code "𝕯" "bldfrakD"           
  , code "𝕰" "bldfrakE"           
  , code "𝕱" "bldfrakF"           
  , code "𝕲" "bldfrakG"           
  , code "𝕳" "bldfrakH"           
  , code "𝕴" "bldfrakI"           
  , code "𝕵" "bldfrakJ"           
  , code "𝕶" "bldfrakK"           
  , code "𝕷" "bldfrakL"           
  , code "𝕸" "bldfrakM"           
  , code "𝕹" "bldfrakN"           
  , code "𝕺" "bldfrakO"           
  , code "𝕻" "bldfrakP"           
  , code "𝕼" "bldfrakQ"           
  , code "𝕽" "bldfrakR"           
  , code "𝕾" "bldfrakS"           
  , code "𝕿" "bldfrakT"           
  , code "𝖀" "bldfrakU"           
  , code "𝖁" "bldfrakV"           
  , code "𝖂" "bldfrakW"           
  , code "𝖃" "bldfrakX"           
  , code "𝖄" "bldfrakY"           
  , code "𝖅" "bldfrakZ"           
  , code "𝖆" "bldfraka"           
  , code "𝖇" "bldfrakb"           
  , code "𝖈" "bldfrakc"           
  , code "𝖉" "bldfrakd"           
  , code "𝖊" "bldfrake"           
  , code "𝖋" "bldfrakf"           
  , code "𝖌" "bldfrakg"           
  , code "𝖍" "bldfrakh"           
  , code "𝖎" "bldfraki"           
  , code "𝖏" "bldfrakj"           
  , code "𝖐" "bldfrakk"           
  , code "𝖑" "bldfrakl"           
  , code "𝖒" "bldfrakm"           
  , code "𝖓" "bldfrakn"           
  , code "𝖔" "bldfrako"           
  , code "𝖕" "bldfrakp"           
  , code "𝖖" "bldfrakq"           
  , code "𝖗" "bldfrakr"           
  , code "𝖘" "bldfraks"           
  , code "𝖙" "bldfrakt"           
  , code "𝖚" "bldfraku"           
  , code "𝖛" "bldfrakv"           
  , code "𝖜" "bldfrakw"           
  , code "𝖝" "bldfrakx"           
  , code "𝖞" "bldfraky"           
  , code "𝖟" "bldfrakz"           

  -- Roman Blackboard Bold
  , code "𝔸" "bbA"           
  , code "𝔹" "bbB"           
  , code "ℂ" "bbC"           
  , code "𝔻" "bbD"           
  , code "𝔼" "bbE"           
  , code "𝔽" "bbF"           
  , code "𝔾" "bbG"           
  , code "ℍ" "bbH"           
  , code "𝕀" "bbI"           
  , code "𝕁" "bbJ"           
  , code "𝕂" "bbK"           
  , code "𝕃" "bbL"           
  , code "𝕄" "bbM"           
  , code "ℕ" "bbN"           
  , code "𝕆" "bbO"           
  , code "ℙ" "bbP"           
  , code "ℚ" "bbQ"           
  , code "ℝ" "bbR"           
  , code "𝕊" "bbS"           
  , code "𝕋" "bbT"           
  , code "𝕌" "bbU"           
  , code "𝕍" "bbV"           
  , code "𝕎" "bbW"           
  , code "𝕏" "bbX"           
  , code "𝕐" "bbY"           
  , code "ℤ" "bbZ"           
  , code "𝕒" "bba"           
  , code "𝕓" "bbb"           
  , code "𝕔" "bbc"           
  , code "𝕕" "bbd"           
  , code "𝕖" "bbe"           
  , code "𝕗" "bbf"           
  , code "𝕘" "bbg"           
  , code "𝕙" "bbh"           
  , code "𝕚" "bbi"           
  , code "𝕛" "bbj"           
  , code "𝕜" "bbk"           
  , code "𝕝" "bbl"           
  , code "𝕞" "bbm"           
  , code "𝕟" "bbn"           
  , code "𝕠" "bbo"           
  , code "𝕡" "bbp"           
  , code "𝕢" "bbq"           
  , code "𝕣" "bbr"           
  , code "𝕤" "bbs"           
  , code "𝕥" "bbt"           
  , code "𝕦" "bbu"           
  , code "𝕧" "bbv"           
  , code "𝕨" "bbw"           
  , code "𝕩" "bbx"           
  , code "𝕪" "bby"           
  , code "𝕫" "bbz"           

  -- Roman Subscripts
  , code "ₐ" "_a"          
  , code "ₑ" "_e"          
  , code "ₕ" "_h"          
  , code "ᵢ" "_i"          
  , code "ⱼ" "_j"          
  , code "ₖ" "_k"          
  , code "ₗ" "_l"          
  , code "ₘ" "_m"          
  , code "ₙ" "_n"          
  , code "ₒ" "_o"          
  , code "ₚ" "_p"          
  , code "ᵣ" "_r"          
  , code "ₛ" "_s"          
  , code "ₜ" "_t"          
  , code "ᵤ" "_u"          
  , code "ᵥ" "_v"          
  , code "ₓ" "_x"          

  -- Roman Superscripts
  , code "ᴬ" "^A"          
  , code "ᴮ" "^B"          
  , code "ᴰ" "^D"          
  , code "ᴱ" "^E"          
  , code "ᴳ" "^G"          
  , code "ᴴ" "^H"          
  , code "ᴵ" "^I"          
  , code "ᴶ" "^J"          
  , code "ᴷ" "^K"          
  , code "ᴸ" "^L"          
  , code "ᴹ" "^M"          
  , code "ᴺ" "^N"          
  , code "ᴼ" "^O"          
  , code "ᴾ" "^P"          
  , code "ᴿ" "^R"          
  , code "ᵀ" "^T"          
  , code "ᵁ" "^U"          
  , code "ⱽ" "^V"          
  , code "ᵂ" "^W"          
  , code "ᵃ" "^a"          
  , code "ᵇ" "^b"          
  , code "ᶜ" "^c"          
  , code "ᵈ" "^d"          
  , code "ᵉ" "^e"          
  , code "ᶠ" "^f"          
  , code "ᵍ" "^g"          
  , code "ʰ" "^h"          
  , code "ⁱ" "^i"          
  , code "ʲ" "^j"          
  , code "ᵏ" "^k"          
  , code "ˡ" "^l"          
  , code "ᵐ" "^m"          
  , code "ⁿ" "^n"          
  , code "ᵒ" "^o"          
  , code "ᵖ" "^p"          
  , code "ʳ" "^r"          
  , code "ˢ" "^s"          
  , code "ᵗ" "^t"          
  , code "ᵘ" "^u"          
  , code "ᵛ" "^v"          
  , code "ʷ" "^w"          
  , code "ˣ" "^x"          
  , code "ʸ" "^y"          
  , code "ᶻ" "^z"          

  -- Roman Small Upper Case
  , code "ᴀ" "smallA"      
  , code "ʙ" "smallB"      
  , code "ᴄ" "smallC"      
  , code "ᴅ" "smallD"      
  , code "ᴇ" "smallE"      
  , code "ꜰ" "smallF"      
  , code "ɢ" "smallG"      
  , code "ʜ" "smallH"      
  , code "ɪ" "smallI"      
  , code "ᴊ" "smallJ"      
  , code "ᴋ" "smallK"      
  , code "ʟ" "smallL"      
  , code "ᴍ" "smallM"      
  , code "ɴ" "smallN"      
  , code "ᴏ" "smallO"      
  , code "ᴘ" "smallP"      
  , code "ʀ" "smallR"      
  , code "ꜱ" "smallS"      
  , code "ᴛ" "smallT"      
  , code "ᴜ" "smallU"      
  , code "ᴠ" "smallV"      
  , code "ᴡ" "smallW"      
  , code "ʏ" "smallY"      
  , code "ᴢ" "smallZ"      

  -- Roman Accents and Gylphs
  , code "é" "e'"          
  , code "è" "e`"          
  , code "ö" "o.."         
  , code "æ" "ae"          
  ]
