noremap! \\ \
noremap! \u ↑
noremap! \r →
noremap! \d ↓
noremap! \l ←
noremap! \ur ↗
noremap! \dr ↘
noremap! \dl ↙
noremap! \ul ↖
noremap! \ud- ↕
noremap! \rl- ↔
noremap! \uu ⇈
noremap! \rr ⇉
noremap! \dd ⇊
noremap! \ll ⇇
noremap! \ud ⇅
noremap! \du ⇵
noremap! \rl ⇄
noremap! \lr ⇆
noremap! \u= ⇑
noremap! \r= ⇒
noremap! \d= ⇓
noremap! \l= ⇐
noremap! \ud= ⇕
noremap! \rl= ⇔
noremap! \r=/ ⇏
noremap! \l=/ ⇍
noremap! \rl=/ ⇎
noremap! \ur= ⇗
noremap! \dr= ⇘
noremap! \dl= ⇙
noremap! \ul= ⇖
noremap! \r== ⇛
noremap! \l== ⇚
noremap! \impr ⟹
noremap! \impl ⟸
noremap! \iff ⟺
noremap! \u\| ⇧
noremap! \r\| ⇨
noremap! \d\| ⇩
noremap! \l\| ⇦
noremap! \rl\| ⬄
noremap! \r\|= ⇰
noremap! \r\\ ⇀
noremap! \u\|- ↥
noremap! \r\|- ↦
noremap! \d\|- ↧
noremap! \l\|- ↤
noremap! \rh ↪
noremap! \lh ↩
noremap! \rc ↬
noremap! \lc ↫
noremap! \r>\| ⇥
noremap! \l>\| ⇤
noremap! \u>> ↟
noremap! \r>> ↠
noremap! \d>> ↡
noremap! \l>> ↞
noremap! \r\|> ⇾
noremap! \l\|> ⇽
noremap! \rl\|> ⇿
noremap! \r~ ↝
noremap! \l~ ↜
noremap! \rl~ ↭
noremap! \rv ↣
noremap! \lv ↢
noremap! \r~~ ⇝
noremap! \l~~ ⇜
noremap! \u. ⇡
noremap! \r. ⇢
noremap! \d. ⇣
noremap! \l. ⇠
noremap! \r/ ↛
noremap! \l/ ↚
noremap! \rl/ ↮
noremap! \ro ⊸
noremap! \lo ⟜
noremap! \rlo ⧟
noremap! \zd ↯
noremap! \cw ↻
noremap! \ccw ↺
noremap! \( ⟮
noremap! \) ⟯
noremap! \(( ⸨
noremap! \)) ⸩
noremap! \(\| ⦇
noremap! \)\| ⦈
noremap! \c( ⦅
noremap! \c) ⦆
noremap! \b( ❪
noremap! \b) ❫
noremap! \B( ❨
noremap! \B) ❩
noremap! \u) ⏜
noremap! \d) ⏝
noremap! \fr ⌢
noremap! \sm ⌣
noremap! \< ⟨
noremap! \> ⟩
noremap! \<< ⟪
noremap! \>> ⟫
noremap! \<\| ⦉
noremap! \>\| ⦊
noremap! \<. ⦑
noremap! \>. ⦒
noremap! \b< ❬
noremap! \b> ❭
noremap! \<" «
noremap! \>" »
noremap! \<' ‹
noremap! \>' ›
noremap! \(< ⦓
noremap! \)> ⦔
noremap! \((> ⦕
noremap! \))< ⦖
noremap! \u< ⸦
noremap! \u> ⸧
noremap! \f< ᚜
noremap! \f> ᚛
noremap! \_< ⸜
noremap! \_> ⸝
noremap! \^< ⸌
noremap! \^> ⸍
noremap! \[ ⦗
noremap! \] ⦘
noremap! \[[ ⟦
noremap! \]] ⟧
noremap! \[\| ⟬
noremap! \]\| ⟭
noremap! \e[ ⁅
noremap! \e] ⁆
noremap! \tL ⌈
noremap! \tR ⌉
noremap! \bL ⌊
noremap! \bR ⌋
noremap! \tl ⸢
noremap! \tr ⸣
noremap! \bl ⸤
noremap! \br ⸥
noremap! \{\| ⦃
noremap! \}\| ⦄
noremap! \{ ⎨
noremap! \} ⎬
noremap! \z{ ⧘
noremap! \z} ⧙
noremap! \z{{ ⧚
noremap! \z}} ⧛
noremap! \b{ ❴
noremap! \b} ❵
noremap! \s{ ⟅
noremap! \s} ⟆
noremap! \</ ≮
noremap! \<= ≤
noremap! \>= ≥
noremap! \<=>= ⋚
noremap! \<~ ≲
noremap! \>~ ≳
noremap! \<? ⩻
noremap! \>? ⩼
noremap! \>< ⪥
noremap! \><x ⪤
noremap! \<2 ≪
noremap! \>2 ≫
noremap! \<3 ⋘
noremap! \>3 ⋙
noremap! \>>= ≫=
noremap! \<<= ≪=
noremap! \xo\| ⊻
noremap! \nand ⊼
noremap! \nor ⊽
noremap! \h< ⪡
noremap! \h> ⪢
noremap! \hor ⩔
noremap! \hand ⩓
noremap! \Hand ⩕
noremap! \Hor ⩖
noremap! \<o ⩹
noremap! \>o ⩺
noremap! \d< ⋖
noremap! \d> ⋗
noremap! \d<= ⩿
noremap! \d>= ⪀
noremap! \dor ⟇
noremap! \dand ⟑
noremap! \m< ⪪
noremap! \m> ⪫
noremap! \m<= ⪬
noremap! \m>= ⪭
noremap! \m<\| ⩤
noremap! \m>\| ⩥
noremap! \mand ⩚
noremap! \mor ⩛
noremap! \e< ≺
noremap! \e> ≻
noremap! \e<- ⪯
noremap! \e>- ⪰
noremap! \e<= ≼
noremap! \e>= ≽
noremap! \eor ⋎
noremap! \eand ⋏
noremap! \e<< ⪻
noremap! \e>> ⪼
noremap! \t<= ⊴
noremap! \t>= ⊵
noremap! \t< ⊲
noremap! \t> ⊳
noremap! \t<> ⧎
noremap! \t<\| ⧏
noremap! \t>\| ⧐
noremap! \t<=/ ⋬
noremap! \t>=/ ⋭
noremap! \ct< ⪦
noremap! \ct> ⪧
noremap! \ct<= ⪨
noremap! \ct>= ⪩
noremap! \ctor ⌔
noremap! \y< ⧼
noremap! \y> ⧽
noremap! \Y< ⊰
noremap! \Y> ⊱
noremap! \s< ⊂
noremap! \s> ⊃
noremap! \s<= ⊆
noremap! \s>= ⊇
noremap! \s<=/ ⊈
noremap! \s>=/ ⊉
noremap! \s</= ⊊
noremap! \s>/= ⊋
noremap! \s</ ⊄
noremap! \s>/ ⊅
noremap! \su ∪
noremap! \si ∩
noremap! \sU ⋃
noremap! \sI ⋂
noremap! \su+ ⊎
noremap! \sU+ ⨄
noremap! \s<. ⪽
noremap! \s>. ⪾
noremap! \su. ⊍
noremap! \si. ⩀
noremap! \s<\| ⫏
noremap! \s>\| ⫐
noremap! \s<=\| ⫑
noremap! \s>=\| ⫒
noremap! \su\| ⩌
noremap! \si\| ⩍
noremap! \hs< ⋐
noremap! \hs> ⋑
noremap! \hsu ⋓
noremap! \hsi ⋒
noremap! \q<= ⊑
noremap! \q>= ⊒
noremap! \q< ⊏
noremap! \q> ⊐
noremap! \q<=/ ⋢
noremap! \q>=/ ⋣
noremap! \q</= ⋤
noremap! \q>/= ⋥
noremap! \j ⊔
noremap! \m ⊓
noremap! \J ⨆
noremap! \M ⨅
noremap! \hj ⩏
noremap! \hm ⩎
noremap! \w ⩊
noremap! \sum ∑
noremap! \prod ∏
noremap! \'< ‘
noremap! \'> ’
noremap! \'` ‛
noremap! \"< “
noremap! \"> ”
noremap! \,, „
noremap! \"` ‟
noremap! \-- –
noremap! \--- —
noremap! \' ′
noremap! \'' ″
noremap! \''' ‴
noremap! \` ‵
noremap! \`` ‶
noremap! \``` ‷
noremap! \. ⋅
noremap! \.bu ∙
noremap! \: ∶
noremap! \:3 ⁝
noremap! \:4 ⁞
noremap! \t: ː
noremap! \s: ꞉
noremap! \ther ∴
noremap! \bec ∵
noremap! \:: ∷
noremap! \.. ‥
noremap! \... …
noremap! \c... ⋯
noremap! \v... ⋮
noremap! \.: ⁖
noremap! \.:. ⁘
noremap! \:.: ⁙
noremap! \.+ ⸭
noremap! \o ∘
noremap! \o: ⦂
noremap! \o; ⨟
noremap! \,\| ⍪
noremap! \d^ ⌄
noremap! \.^ ˙
noremap! \and, ꘍
noremap! \\| ∣
noremap! \\|/ ∤
noremap! \\|: ¦
noremap! \w\| ⫾
noremap! \\|\| ‖
noremap! \par ∥
noremap! \% ÷
noremap! \%% ٪
noremap! \/ ∕
noremap! \set\\ ∖
noremap! \// ⫽
noremap! \& ⅋
noremap! \/// ⫻
noremap! \O/ ∅
noremap! \* ⋆
noremap! \star ☆
noremap! \starb ★
noremap! \** ⋇
noremap! \# ♯
noremap! \## 𝄪
noremap! \b ♭
noremap! \bb 𝄫
noremap! \n ♮
noremap! \=\|\| ⋕
noremap! \d? ¿
noremap! \d! ¡
noremap! \?? ⁇
noremap! \!! ‼
noremap! \?! ⁈
noremap! \!? ⁉
noremap! \++ ⧺
noremap! \+++ ⧻
noremap! \+. ∔
noremap! \+( ⨭
noremap! \+) ⨮
noremap! \+- ±
noremap! \-. ∸
noremap! \x ×
noremap! \x. ⨰
noremap! \x- ⨱
noremap! \x( ⨴
noremap! \x) ⨵
noremap! \xx ⨯
noremap! \XX ⨳
noremap! \xb ✖
noremap! \swap ⤨
noremap! \o+ ⊕
noremap! \o- ⊖
noremap! \ox ⊗
noremap! \o/ ⊘
noremap! \o. ⊙
noremap! \oo ⊚
noremap! \o* ⊛
noremap! \o= ⊜
noremap! \o-- ⊝
noremap! \ot ⎊
noremap! \o\| ⦶
noremap! \o\|\| ⦷
noremap! \o\\ ⦸
noremap! \obot ⦹
noremap! \o% ⦼
noremap! \o< ⧀
noremap! \o> ⧁
noremap! \.di ⋄
noremap! \di ◇
noremap! \di. ⟐
noremap! \s □
noremap! \s+ ⊞
noremap! \s- ⊟
noremap! \sx ⊠
noremap! \s. ⊡
noremap! \sand ⟎
noremap! \sor ⟏
noremap! \s/ ⧄
noremap! \s\\ ⧅
noremap! \s* ⧆
noremap! \so ⧇
noremap! \ss ⧈
noremap! \sss ⧉
noremap! \s\| ⎅
noremap! \O ○
noremap! \qed ∎
noremap! \-/ ⌿
noremap! \sin ∿
noremap! \link ∾
noremap! \bow ⋈
noremap! \hour ⧖
noremap! \bowl ⋉
noremap! \bowr ⋊
noremap! \inf ∞
noremap! \inf< ∝
noremap! \tru △
noremap! \trr ▷
noremap! \trd ▽
noremap! \trl ◁
noremap! \trub ▲
noremap! \trrb ▶
noremap! \trdb ▼
noremap! \trlb ◀
noremap! \t+ ⨹
noremap! \t- ⨺
noremap! \tx ⨻
noremap! \tt ⟁
noremap! \t. ◬
noremap! \cd ⟡
noremap! \cd> ⟢
noremap! \cd< ⟣
noremap! \sq> ⟤
noremap! \sq< ⟥
noremap! \loz ⌑
noremap! \d<> ⟠
noremap! \zap ⌁
noremap! \dag †
noremap! \ddag ‡
noremap! \*** ⁂
noremap! \int ∫
noremap! \cent ¢
noremap! \Oo ⧂
noremap! \+br ⌌
noremap! \+bl ⌍
noremap! \+tr ⌎
noremap! \+tl ⌏
noremap! \ctl ⌜
noremap! \ctr ⌝
noremap! \cbl ⌞
noremap! \cbr ⌟
noremap! \>- ⌲
noremap! \scales ⚖
noremap! \root √
noremap! \in ∈
noremap! \in. ⋵
noremap! \in\| ⋳
noremap! \in= ⋹
noremap! \in- ⋲
noremap! \in-l ⋺
noremap! \in/ ∉
noremap! \inl ∋
noremap! \in\|l ⋻
noremap! \inu ⟒
noremap! \ind ⫙
noremap! \ele ∊
noremap! \elel ∍
noremap! \ele\| ⋴
noremap! \ele\|l ⋼
noremap! \mem ⋿
noremap! \all ∀
noremap! \ex ∃
noremap! \ex/ ∄
noremap! \\|- ⊢
noremap! \-\| ⊣
noremap! \\|= ⊨
noremap! \or ∨
noremap! \and ∧
noremap! \andor ⩙
noremap! \bot ⊥
noremap! \bot= ⫫
noremap! \top ⊤
noremap! \not ¬
noremap! \xor ⊻
noremap! \comp ∁
noremap! \== ≡
noremap! \==/ ≢
noremap! \=== ≣
noremap! \=2 ⩵
noremap! \=3 ⩶
noremap! \~= ≃
noremap! \~~ ≈
noremap! \~~/ ≉
noremap! \~ ∼
noremap! \~/ ≁
noremap! \:= ≔
noremap! \=: ≕
noremap! \::= ⩴
noremap! \=/ ≠
noremap! \=? ≟
noremap! \=o ≗
noremap! \=* ⩮
noremap! \=. ⩦
noremap! \=// ⧣
noremap! \=s ≌
noremap! \=star ≛
noremap! \~~^ ⩯
noremap! \=t ≜
noremap! \=def ≝
noremap! \eqv ≍
noremap! \eqv/ ≭
noremap! \=O ≎
noremap! \block █
noremap! \_+ ₊
noremap! \_- ₋
noremap! \_= ₌
noremap! \_( ₍
noremap! \_) ₎
noremap! \^+ ⁺
noremap! \^- ⁻
noremap! \^= ⁼
noremap! \^( ⁽
noremap! \^) ⁾
noremap! \^deg ˚
noremap! \^bow ⑅
noremap! \^uu ᐜ
noremap! \^tr ᐞ
noremap! \^/ ᐟ
noremap! \^\ ᐠ
noremap! \^un ᐡ
noremap! \^in ᐢ
noremap! \^su ᐣ
noremap! \^// ᐥ
noremap! \^\|\| ᐦ
noremap! \^top ᐪ
noremap! \^. ᐧ
noremap! \^^nu ֮
noremap! \^^^ ̂
noremap! \^^< ᷾
noremap! \^^> ͐
noremap! \^^<- ⃖
noremap! \^^-> ⃗
noremap! \^^~ ̃
noremap! \^^( ̑
noremap! \^^) ̆
noremap! \^^~~ ͌
noremap! \^^- ̄
noremap! \^^-- ̅
noremap! \^^. ̇
noremap! \^^.. ̈
noremap! \^^o ̊
noremap! \^^, ̉
noremap! \^^v ̌
noremap! \^^(. ̐
noremap! \PP ¶
noremap! \_ ␣
noremap! \__ ‗
noremap! \___ ﹍
noremap! \~_ ﹏
noremap! \utie ‿
noremap! \iutie ⁔
noremap! \sp ␠
noremap! \SS §
noremap! \bu •
noremap! \obu ◦
noremap! \-bu ⁃
noremap! \tbu ‣
noremap! \lbu ⁌
noremap! \rbu ⁍
noremap! \ibu ◘
noremap! \hbu ❥
noremap! \hlbu ☙
noremap! \hrbu ❧
noremap! \buo ⦿
noremap! \obuo ⦾
noremap! \check ✓
noremap! \X ✗
noremap! \bal ☐
noremap! \balc ☑
noremap! \balx ☒
noremap! \disapprove ಠ_ಠ
noremap! \flip ﹙╯°□°）╯︵┻━┻
noremap! \putback ┬─┬ノ﹙゜-゜ノ﹚
noremap! \dust ┬─┬⃰͡ ﹙ᵔᵕᵔ͜ ﹚
noremap! \doubleflip ┻━┻︵ヽ﹙`Д´﹚ﾉ︵┻━┻
noremap! \fisticuffs ლ﹙｀ー´ლ﹚
noremap! \shrug ¯\_﹙ツ﹚_/¯
noremap! \meh ¯\﹙°_o﹚/¯
noremap! \angry ﹙╬ಠ益ಠ﹚
noremap! \meow ฅ^•ﻌ•^ฅ
noremap! \cheers ﹙^_^）o自自o（^_^﹚
noremap! \crying ಥ_ಥ
noremap! \breakdown ಥ﹏ಥ
noremap! \disagree ٩◔̯◔۶
noremap! \flex ᕙ﹙⇀‸↼‶﹚ᕗ
noremap! \sadconfused ¯\_﹙⊙︿⊙﹚_/¯
noremap! \ytho щ（ﾟДﾟщ）
noremap! \strut ᕕ﹙ᐛ﹚ᕗ
noremap! \fkit t﹙-_-t﹚
noremap! \sleepy 눈_눈
noremap! \opera ヾ﹙´〇`﹚ﾉ♪♪♪
noremap! \zombie [¬º-°]¬
noremap! \point ﹙☞ﾟヮﾟ﹚☞
noremap! \poo 💩
noremap! \Alpha Α
noremap! \Beta Β
noremap! \Gamma Γ
noremap! \Delta Δ
noremap! \Epsilon Ε
noremap! \Zeta Ζ
noremap! \Eta Η
noremap! \Theta Θ
noremap! \Iota Ι
noremap! \Kappa Κ
noremap! \Lambda Λ
noremap! \Mu Μ
noremap! \Nu Ν
noremap! \Xi Ξ
noremap! \Omicron Ο
noremap! \Pi Π
noremap! \Rho Ρ
noremap! \varSigma ϴ
noremap! \Sigma Σ
noremap! \Tau Τ
noremap! \Upsilon Υ
noremap! \Phi Φ
noremap! \Chi Χ
noremap! \Psi Ψ
noremap! \Omega Ω
noremap! \Nabla ∇
noremap! \alpha α
noremap! \beta β
noremap! \gamma γ
noremap! \delta δ
noremap! \epsilon ε
noremap! \zeta ζ
noremap! \eta η
noremap! \theta θ
noremap! \iota ι
noremap! \kappa κ
noremap! \lambda λ
noremap! \mu μ
noremap! \nu ν
noremap! \xi ξ
noremap! \omicron ο
noremap! \pi π
noremap! \rho ρ
noremap! \varsigma ς
noremap! \sigma σ
noremap! \tau τ
noremap! \upsilon υ
noremap! \phi φ
noremap! \chi χ
noremap! \psi ψ
noremap! \omega ω
noremap! \nabla ∂
noremap! \varepsilon ϵ
noremap! \vartheta ϑ
noremap! \varkappa ϰ
noremap! \varphi ϕ
noremap! \varrho ϱ
noremap! \varpi ϖ
noremap! \lambda/ ƛ
noremap! \bdAlpha 𝚨
noremap! \bdBeta 𝚩
noremap! \bdGamma 𝚪
noremap! \bdDelta 𝚫
noremap! \bdEpsilon 𝚬
noremap! \bdZeta 𝚭
noremap! \bdEta 𝚮
noremap! \bdTheta 𝚯
noremap! \bdIota 𝚰
noremap! \bdKappa 𝚱
noremap! \bdLambda 𝚲
noremap! \bdMu 𝚳
noremap! \bdNu 𝚴
noremap! \bdXi 𝚵
noremap! \bdOmicron 𝚶
noremap! \bdPi 𝚷
noremap! \bdRho 𝚸
noremap! \bdvarSigma 𝚹
noremap! \bdSigma 𝚺
noremap! \bdTau 𝚻
noremap! \bdUpsilon 𝚼
noremap! \bdPhi 𝚽
noremap! \bdChi 𝚾
noremap! \bdPsi 𝚿
noremap! \bdOmega 𝛀
noremap! \bdNabla 𝛁
noremap! \bdalpha 𝛂
noremap! \bdbeta 𝛃
noremap! \bdgamma 𝛄
noremap! \bddelta 𝛅
noremap! \bdepsilon 𝛆
noremap! \bdzeta 𝛇
noremap! \bdldeta 𝛈
noremap! \bdtheta 𝛉
noremap! \bdiota 𝛊
noremap! \bdkappa 𝛋
noremap! \bdlambda 𝛌
noremap! \bdmu 𝛍
noremap! \bdnu 𝛎
noremap! \bdxi 𝛏
noremap! \bdomicron 𝛐
noremap! \bdpi 𝛑
noremap! \bdrho 𝛒
noremap! \bdvarsigma 𝛓
noremap! \bdsigma 𝛔
noremap! \bdtau 𝛕
noremap! \bdupsilon 𝛖
noremap! \bdphi 𝛗
noremap! \bdchi 𝛘
noremap! \bdpsi 𝛙
noremap! \bdomega 𝛚
noremap! \bdnabla 𝛛
noremap! \bdvarepsilon 𝛜
noremap! \bdvartheta 𝛝
noremap! \bdvarkappa 𝛞
noremap! \bdvarphi 𝛟
noremap! \bdvarrho 𝛠
noremap! \bdvarpi 𝛡
noremap! \itAlpha 𝛢
noremap! \itBeta 𝛣
noremap! \itGamma 𝛤
noremap! \itDelta 𝛥
noremap! \itEpsilon 𝛦
noremap! \itZeta 𝛧
noremap! \itEta 𝛨
noremap! \itTheta 𝛩
noremap! \itIota 𝛪
noremap! \itKappa 𝛫
noremap! \itLambda 𝛬
noremap! \itMu 𝛭
noremap! \itNu 𝛮
noremap! \itXi 𝛯
noremap! \itOmicron 𝛰
noremap! \itPi 𝛱
noremap! \itRho 𝛲
noremap! \itvarSigma 𝛳
noremap! \itSigma 𝛴
noremap! \itTau 𝛵
noremap! \itUpsilon 𝛶
noremap! \itPhi 𝛷
noremap! \itChi 𝛸
noremap! \itPsi 𝛹
noremap! \itOmega 𝛺
noremap! \itNabla 𝛻
noremap! \italpha 𝛼
noremap! \itbeta 𝛽
noremap! \itgamma 𝛾
noremap! \itdelta 𝛿
noremap! \itepsilon 𝜀
noremap! \itzeta 𝜁
noremap! \iteta 𝜂
noremap! \ittheta 𝜃
noremap! \itiota 𝜄
noremap! \itkappa 𝜅
noremap! \itlambda 𝜆
noremap! \itmu 𝜇
noremap! \itnu 𝜈
noremap! \itxi 𝜉
noremap! \itomicron 𝜊
noremap! \itpi 𝜋
noremap! \itrho 𝜌
noremap! \itvarsigma 𝜍
noremap! \itsigma 𝜎
noremap! \ittau 𝜏
noremap! \itupsilon 𝜐
noremap! \itphi 𝜑
noremap! \itchi 𝜒
noremap! \itpsi 𝜓
noremap! \itomega 𝜔
noremap! \itnabla 𝜕
noremap! \itvarepsilon 𝜖
noremap! \itvartheta 𝜗
noremap! \itvarkappa 𝜘
noremap! \itvarphi 𝜙
noremap! \itvarrho 𝜚
noremap! \itvarpi 𝜛
noremap! \bditAlpha 𝜜
noremap! \bditBeta 𝜝
noremap! \bditGamma 𝜞
noremap! \bditDelta 𝜟
noremap! \bditEpsilon 𝜠
noremap! \bditZeta 𝜡
noremap! \bditEta 𝜢
noremap! \bditTheta 𝜣
noremap! \bditIota 𝜤
noremap! \bditKappa 𝜥
noremap! \bditLambda 𝜦
noremap! \bditMu 𝜧
noremap! \bditNu 𝜨
noremap! \bditXi 𝜩
noremap! \bditOmicron 𝜪
noremap! \bditPi 𝜫
noremap! \bditRho 𝜬
noremap! \bditvarSigma 𝜭
noremap! \bditSigma 𝜮
noremap! \bditTau 𝜯
noremap! \bditUpsilon 𝜰
noremap! \bditPhi 𝜱
noremap! \bditChi 𝜲
noremap! \bditPsi 𝜳
noremap! \bditOmega 𝜴
noremap! \bditNabla 𝜵
noremap! \bditalpha 𝜶
noremap! \bditbeta 𝜷
noremap! \bditgamma 𝜸
noremap! \bditdelta 𝜹
noremap! \bditepsilon 𝜺
noremap! \bditzeta 𝜻
noremap! \bditeta 𝜼
noremap! \bdittheta 𝜽
noremap! \bditiota 𝜾
noremap! \bditkappa 𝜿
noremap! \bditlambda 𝝀
noremap! \bditmu 𝝁
noremap! \bditnu 𝝂
noremap! \bditxi 𝝃
noremap! \bditomicron 𝝄
noremap! \bditpi 𝝅
noremap! \bditrho 𝝆
noremap! \bditvarsigma 𝝇
noremap! \bditsigma 𝝈
noremap! \bdittau 𝝉
noremap! \bditupsilon 𝝊
noremap! \bditphi 𝝋
noremap! \bditchi 𝝌
noremap! \bditpsi 𝝍
noremap! \bditomega 𝝎
noremap! \bditnabla 𝝏
noremap! \bditvarepsilon 𝝐
noremap! \bditvartheta 𝝑
noremap! \bditvarkappa 𝝒
noremap! \bditvarphi 𝝓
noremap! \bditvarrho 𝝔
noremap! \bditvarpi 𝝕
noremap! \_beta ᵦ
noremap! \_gamma ᵧ
noremap! \_rho ᵨ
noremap! \_phi ᵩ
noremap! \_chi ᵪ
noremap! \^alpha ᵅ
noremap! \^beta ᵝ
noremap! \^gamma ᵞ
noremap! \^delta ᵟ
noremap! \^epsilon ᵋ
noremap! \^theta ᶿ
noremap! \^iota ᶥ
noremap! \^Phi ᶲ
noremap! \^phi ᵠ
noremap! \^chi ᵡ
noremap! \bbGamma ℾ
noremap! \bbgamma ℽ
noremap! \bbPi ℿ
noremap! \bbpi ℼ
noremap! \bbSigma ⅀
noremap! \bd0 𝟎
noremap! \bd1 𝟏
noremap! \bd2 𝟐
noremap! \bd3 𝟑
noremap! \bd4 𝟒
noremap! \bd5 𝟓
noremap! \bd6 𝟔
noremap! \bd7 𝟕
noremap! \bd8 𝟖
noremap! \bd9 𝟗
noremap! \bb0 𝟘
noremap! \bb1 𝟙
noremap! \bb2 𝟚
noremap! \bb3 𝟛
noremap! \bb4 𝟜
noremap! \bb5 𝟝
noremap! \bb6 𝟞
noremap! \bb7 𝟟
noremap! \bb8 𝟠
noremap! \bb9 𝟡
noremap! \_0 ₀
noremap! \_1 ₁
noremap! \_2 ₂
noremap! \_3 ₃
noremap! \_4 ₄
noremap! \_5 ₅
noremap! \_6 ₆
noremap! \_7 ₇
noremap! \_8 ₈
noremap! \_9 ₉
noremap! \^0 ⁰
noremap! \^1 ¹
noremap! \^2 ²
noremap! \^3 ³
noremap! \^4 ⁴
noremap! \^5 ⁵
noremap! \^6 ⁶
noremap! \^7 ⁷
noremap! \^8 ⁸
noremap! \^9 ⁹
noremap! \1/2 ½
noremap! \0/3 ↉
noremap! \1/3 ⅓
noremap! \2/3 ⅔
noremap! \1/4 ¼
noremap! \3/4 ¾
noremap! \1/5 ⅕
noremap! \2/5 ⅖
noremap! \3/5 ⅗
noremap! \4/5 ⅘
noremap! \1/6 ⅙
noremap! \5/6 ⅚
noremap! \1/7 ⅐
noremap! \1/8 ⅛
noremap! \3/8 ⅜
noremap! \5/8 ⅝
noremap! \7/8 ⅞
noremap! \1/9 ⅑
noremap! \1/10 ⅒
noremap! \wp ℘
noremap! \ell ℓ
noremap! \ln ㏑
noremap! \log ㏒
noremap! \bdA 𝐀
noremap! \bdB 𝐁
noremap! \bdC 𝐂
noremap! \bdD 𝐃
noremap! \bdE 𝐄
noremap! \bdF 𝐅
noremap! \bdG 𝐆
noremap! \bdH 𝐇
noremap! \bdI 𝐈
noremap! \bdJ 𝐉
noremap! \bdK 𝐊
noremap! \bdL 𝐋
noremap! \bdM 𝐌
noremap! \bdN 𝐍
noremap! \bdO 𝐎
noremap! \bdP 𝐏
noremap! \bdQ 𝐐
noremap! \bdR 𝐑
noremap! \bdS 𝐒
noremap! \bdT 𝐓
noremap! \bdU 𝐔
noremap! \bdV 𝐕
noremap! \bdW 𝐖
noremap! \bdX 𝐗
noremap! \bdY 𝐘
noremap! \bdZ 𝐙
noremap! \bda 𝐚
noremap! \bdb 𝐛
noremap! \bdc 𝐜
noremap! \bdd 𝐝
noremap! \bde 𝐞
noremap! \bdf 𝐟
noremap! \bdg 𝐠
noremap! \bdh 𝐡
noremap! \bdi 𝐢
noremap! \bdj 𝐣
noremap! \bdk 𝐤
noremap! \bdl 𝐥
noremap! \bdm 𝐦
noremap! \bdn 𝐧
noremap! \bdo 𝐨
noremap! \bdp 𝐩
noremap! \bdq 𝐪
noremap! \bdr 𝐫
noremap! \bds 𝐬
noremap! \bdt 𝐭
noremap! \bdu 𝐮
noremap! \bdv 𝐯
noremap! \bdw 𝐰
noremap! \bdx 𝐱
noremap! \bdy 𝐲
noremap! \bdz 𝐳
noremap! \itA 𝐴
noremap! \itB 𝐵
noremap! \itC 𝐶
noremap! \itD 𝐷
noremap! \itE 𝐸
noremap! \itF 𝐹
noremap! \itG 𝐺
noremap! \itH 𝐻
noremap! \itI 𝐼
noremap! \itJ 𝐽
noremap! \itK 𝐾
noremap! \itL 𝐿
noremap! \itM 𝑀
noremap! \itN 𝑁
noremap! \itO 𝑂
noremap! \itP 𝑃
noremap! \itQ 𝑄
noremap! \itR 𝑅
noremap! \itS 𝑆
noremap! \itT 𝑇
noremap! \itU 𝑈
noremap! \itV 𝑉
noremap! \itW 𝑊
noremap! \itX 𝑋
noremap! \itY 𝑌
noremap! \itZ 𝑍
noremap! \ita 𝑎
noremap! \itb 𝑏
noremap! \itc 𝑐
noremap! \itd 𝑑
noremap! \ite 𝑒
noremap! \itf 𝑓
noremap! \itg 𝑔
noremap! \ith ℎ
noremap! \iti 𝑖
noremap! \itj 𝑗
noremap! \itk 𝑘
noremap! \itl 𝑙
noremap! \itm 𝑚
noremap! \itn 𝑛
noremap! \ito 𝑜
noremap! \itp 𝑝
noremap! \itq 𝑞
noremap! \itr 𝑟
noremap! \its 𝑠
noremap! \itt 𝑡
noremap! \itu 𝑢
noremap! \itv 𝑣
noremap! \itw 𝑤
noremap! \itx 𝑥
noremap! \ity 𝑦
noremap! \itz 𝑧
noremap! \bditA 𝑨
noremap! \bditB 𝑩
noremap! \bditC 𝑪
noremap! \bditD 𝑫
noremap! \bditE 𝑬
noremap! \bditF 𝑭
noremap! \bditG 𝑮
noremap! \bditH 𝑯
noremap! \bditI 𝑰
noremap! \bditJ 𝑱
noremap! \bditK 𝑲
noremap! \bditL 𝑳
noremap! \bditM 𝑴
noremap! \bditN 𝑵
noremap! \bditO 𝑶
noremap! \bditP 𝑷
noremap! \bditQ 𝑸
noremap! \bditR 𝑹
noremap! \bditS 𝑺
noremap! \bditT 𝑻
noremap! \bditU 𝑼
noremap! \bditV 𝑽
noremap! \bditW 𝑾
noremap! \bditX 𝑿
noremap! \bditY 𝒀
noremap! \bditZ 𝒁
noremap! \bdita 𝒂
noremap! \bditb 𝒃
noremap! \bditc 𝒄
noremap! \bditd 𝒅
noremap! \bdite 𝒆
noremap! \bditf 𝒇
noremap! \bditg 𝒈
noremap! \bdith 𝒉
noremap! \bditi 𝒊
noremap! \bditj 𝒋
noremap! \bditk 𝒌
noremap! \bditl 𝒍
noremap! \bditm 𝒎
noremap! \bditn 𝒏
noremap! \bdito 𝒐
noremap! \bditp 𝒑
noremap! \bditq 𝒒
noremap! \bditr 𝒓
noremap! \bdits 𝒔
noremap! \bditt 𝒕
noremap! \bditu 𝒖
noremap! \bditv 𝒗
noremap! \bditw 𝒘
noremap! \bditx 𝒙
noremap! \bdity 𝒚
noremap! \bditz 𝒛
noremap! \calA 𝒜
noremap! \calB ℬ
noremap! \calC 𝒞
noremap! \calD 𝒟
noremap! \calE ℰ
noremap! \calF ℱ
noremap! \calG 𝒢
noremap! \calH ℋ
noremap! \calI ℐ
noremap! \calJ 𝒥
noremap! \calK 𝒦
noremap! \calL ℒ
noremap! \calM ℳ
noremap! \calN 𝒩
noremap! \calO 𝒪
noremap! \calP 𝒫
noremap! \calQ 𝒬
noremap! \calR ℛ
noremap! \calS 𝒮
noremap! \calT 𝒯
noremap! \calU 𝒰
noremap! \calV 𝒱
noremap! \calW 𝒲
noremap! \calX 𝒳
noremap! \calY 𝒴
noremap! \calZ 𝒵
noremap! \cala 𝒶
noremap! \calb 𝒷
noremap! \calc 𝒸
noremap! \cald 𝒹
noremap! \cale ℯ
noremap! \calf 𝒻
noremap! \calg ℊ
noremap! \calh 𝒽
noremap! \cali 𝒾
noremap! \calj 𝒿
noremap! \calk 𝓀
noremap! \call 𝓁
noremap! \calm 𝓂
noremap! \caln 𝓃
noremap! \calo ℴ
noremap! \calp 𝓅
noremap! \calq 𝓆
noremap! \calr 𝓇
noremap! \cals 𝓈
noremap! \calt 𝓉
noremap! \calu 𝓊
noremap! \calv 𝓋
noremap! \calw 𝓌
noremap! \calx 𝓍
noremap! \caly 𝓎
noremap! \calz 𝓏
noremap! \bdcalA 𝓐
noremap! \bdcalB 𝓑
noremap! \bdcalC 𝓒
noremap! \bdcalD 𝓓
noremap! \bdcalE 𝓔
noremap! \bdcalF 𝓕
noremap! \bdcalG 𝓖
noremap! \bdcalH 𝓗
noremap! \bdcalI 𝓘
noremap! \bdcalJ 𝓙
noremap! \bdcalK 𝓚
noremap! \bdcalL 𝓛
noremap! \bdcalM 𝓜
noremap! \bdcalN 𝓝
noremap! \bdcalO 𝓞
noremap! \bdcalP 𝓟
noremap! \bdcalQ 𝓠
noremap! \bdcalR 𝓡
noremap! \bdcalS 𝓢
noremap! \bdcalT 𝓣
noremap! \bdcalU 𝓤
noremap! \bdcalV 𝓥
noremap! \bdcalW 𝓦
noremap! \bdcalX 𝓧
noremap! \bdcalY 𝓨
noremap! \bdcalZ 𝓩
noremap! \bdcala 𝓪
noremap! \bdcalb 𝓫
noremap! \bdcalc 𝓬
noremap! \bdcald 𝓭
noremap! \bdcale 𝓮
noremap! \bdcalf 𝓯
noremap! \bdcalg 𝓰
noremap! \bdcalh 𝓱
noremap! \bdcali 𝓲
noremap! \bdcalj 𝓳
noremap! \bdcalk 𝓴
noremap! \bdcall 𝓵
noremap! \bdcalm 𝓶
noremap! \bdcaln 𝓷
noremap! \bdcalo 𝓸
noremap! \bdcalp 𝓹
noremap! \bdcalq 𝓺
noremap! \bdcalr 𝓻
noremap! \bdcals 𝓼
noremap! \bdcalt 𝓽
noremap! \bdcalu 𝓾
noremap! \bdcalv 𝓿
noremap! \bdcalw 𝔀
noremap! \bdcalx 𝔁
noremap! \bdcaly 𝔂
noremap! \bdcalz 𝔃
noremap! \frakA 𝔄
noremap! \frakB 𝔅
noremap! \frakC ℭ
noremap! \frakD 𝔇
noremap! \frakE 𝔈
noremap! \frakF 𝔉
noremap! \frakG 𝔊
noremap! \frakH ℌ
noremap! \frakI ℑ
noremap! \frakJ 𝔍
noremap! \frakK 𝔎
noremap! \frakL 𝔏
noremap! \frakM 𝔐
noremap! \frakN 𝔑
noremap! \frakO 𝔒
noremap! \frakP 𝔓
noremap! \frakQ 𝔔
noremap! \frakR ℜ
noremap! \frakS 𝔖
noremap! \frakT 𝔗
noremap! \frakU 𝔘
noremap! \frakV 𝔙
noremap! \frakW 𝔚
noremap! \frakX 𝔛
noremap! \frakY 𝔜
noremap! \frakZ ℨ
noremap! \fraka 𝔞
noremap! \frakb 𝔟
noremap! \frakc 𝔠
noremap! \frakd 𝔡
noremap! \frake 𝔢
noremap! \frakf 𝔣
noremap! \frakg 𝔤
noremap! \frakh 𝔥
noremap! \fraki 𝔦
noremap! \frakj 𝔧
noremap! \frakk 𝔨
noremap! \frakl 𝔩
noremap! \frakm 𝔪
noremap! \frakn 𝔫
noremap! \frako 𝔬
noremap! \frakp 𝔭
noremap! \frakq 𝔮
noremap! \frakr 𝔯
noremap! \fraks 𝔰
noremap! \frakt 𝔱
noremap! \fraku 𝔲
noremap! \frakv 𝔳
noremap! \frakw 𝔴
noremap! \frakx 𝔵
noremap! \fraky 𝔶
noremap! \frakz 𝔷
noremap! \bdfrakA 𝕬
noremap! \bdfrakB 𝕭
noremap! \bdfrakC 𝕮
noremap! \bdfrakD 𝕯
noremap! \bdfrakE 𝕰
noremap! \bdfrakF 𝕱
noremap! \bdfrakG 𝕲
noremap! \bdfrakH 𝕳
noremap! \bdfrakI 𝕴
noremap! \bdfrakJ 𝕵
noremap! \bdfrakK 𝕶
noremap! \bdfrakL 𝕷
noremap! \bdfrakM 𝕸
noremap! \bdfrakN 𝕹
noremap! \bdfrakO 𝕺
noremap! \bdfrakP 𝕻
noremap! \bdfrakQ 𝕼
noremap! \bdfrakR 𝕽
noremap! \bdfrakS 𝕾
noremap! \bdfrakT 𝕿
noremap! \bdfrakU 𝖀
noremap! \bdfrakV 𝖁
noremap! \bdfrakW 𝖂
noremap! \bdfrakX 𝖃
noremap! \bdfrakY 𝖄
noremap! \bdfrakZ 𝖅
noremap! \bdfraka 𝖆
noremap! \bdfrakb 𝖇
noremap! \bdfrakc 𝖈
noremap! \bdfrakd 𝖉
noremap! \bdfrake 𝖊
noremap! \bdfrakf 𝖋
noremap! \bdfrakg 𝖌
noremap! \bdfrakh 𝖍
noremap! \bdfraki 𝖎
noremap! \bdfrakj 𝖏
noremap! \bdfrakk 𝖐
noremap! \bdfrakl 𝖑
noremap! \bdfrakm 𝖒
noremap! \bdfrakn 𝖓
noremap! \bdfrako 𝖔
noremap! \bdfrakp 𝖕
noremap! \bdfrakq 𝖖
noremap! \bdfrakr 𝖗
noremap! \bdfraks 𝖘
noremap! \bdfrakt 𝖙
noremap! \bdfraku 𝖚
noremap! \bdfrakv 𝖛
noremap! \bdfrakw 𝖜
noremap! \bdfrakx 𝖝
noremap! \bdfraky 𝖞
noremap! \bdfrakz 𝖟
noremap! \bbA 𝔸
noremap! \bbB 𝔹
noremap! \bbC ℂ
noremap! \bbD 𝔻
noremap! \bbE 𝔼
noremap! \bbF 𝔽
noremap! \bbG 𝔾
noremap! \bbH ℍ
noremap! \bbI 𝕀
noremap! \bbJ 𝕁
noremap! \bbK 𝕂
noremap! \bbL 𝕃
noremap! \bbM 𝕄
noremap! \bbN ℕ
noremap! \bbO 𝕆
noremap! \bbP ℙ
noremap! \bbQ ℚ
noremap! \bbR ℝ
noremap! \bbS 𝕊
noremap! \bbT 𝕋
noremap! \bbU 𝕌
noremap! \bbV 𝕍
noremap! \bbW 𝕎
noremap! \bbX 𝕏
noremap! \bbY 𝕐
noremap! \bbZ ℤ
noremap! \bba 𝕒
noremap! \bbb 𝕓
noremap! \bbc 𝕔
noremap! \bbd 𝕕
noremap! \bbe 𝕖
noremap! \bbf 𝕗
noremap! \bbg 𝕘
noremap! \bbh 𝕙
noremap! \bbi 𝕚
noremap! \bbj 𝕛
noremap! \bbk 𝕜
noremap! \bbl 𝕝
noremap! \bbm 𝕞
noremap! \bbn 𝕟
noremap! \bbo 𝕠
noremap! \bbp 𝕡
noremap! \bbq 𝕢
noremap! \bbr 𝕣
noremap! \bbs 𝕤
noremap! \bbt 𝕥
noremap! \bbu 𝕦
noremap! \bbv 𝕧
noremap! \bbw 𝕨
noremap! \bbx 𝕩
noremap! \bby 𝕪
noremap! \bbz 𝕫
noremap! \_a ₐ
noremap! \_e ₑ
noremap! \_h ₕ
noremap! \_i ᵢ
noremap! \_j ⱼ
noremap! \_k ₖ
noremap! \_l ₗ
noremap! \_m ₘ
noremap! \_n ₙ
noremap! \_o ₒ
noremap! \_p ₚ
noremap! \_r ᵣ
noremap! \_s ₛ
noremap! \_t ₜ
noremap! \_u ᵤ
noremap! \_v ᵥ
noremap! \_x ₓ
noremap! \^A ᴬ
noremap! \^B ᴮ
noremap! \^D ᴰ
noremap! \^E ᴱ
noremap! \^G ᴳ
noremap! \^H ᴴ
noremap! \^I ᴵ
noremap! \^J ᴶ
noremap! \^K ᴷ
noremap! \^L ᴸ
noremap! \^M ᴹ
noremap! \^N ᴺ
noremap! \^O ᴼ
noremap! \^P ᴾ
noremap! \^R ᴿ
noremap! \^T ᵀ
noremap! \^U ᵁ
noremap! \^V ⱽ
noremap! \^W ᵂ
noremap! \^a ᵃ
noremap! \^b ᵇ
noremap! \^c ᶜ
noremap! \^d ᵈ
noremap! \^e ᵉ
noremap! \^f ᶠ
noremap! \^g ᵍ
noremap! \^h ʰ
noremap! \^i ⁱ
noremap! \^j ʲ
noremap! \^k ᵏ
noremap! \^l ˡ
noremap! \^m ᵐ
noremap! \^n ⁿ
noremap! \^o ᵒ
noremap! \^p ᵖ
noremap! \^q ᶝ
noremap! \^r ʳ
noremap! \^s ˢ
noremap! \^t ᵗ
noremap! \^u ᵘ
noremap! \^v ᵛ
noremap! \^w ʷ
noremap! \^x ˣ
noremap! \^y ʸ
noremap! \^z ᶻ
noremap! \^tm ™
noremap! \sca ᴀ
noremap! \scb ʙ
noremap! \scc ᴄ
noremap! \scd ᴅ
noremap! \sce ᴇ
noremap! \scf ꜰ
noremap! \scg ɢ
noremap! \sch ʜ
noremap! \sci ɪ
noremap! \scj ᴊ
noremap! \sck ᴋ
noremap! \scl ʟ
noremap! \scm ᴍ
noremap! \scn ɴ
noremap! \sco ᴏ
noremap! \scp ᴘ
noremap! \scr ʀ
noremap! \scs ꜱ
noremap! \sct ᴛ
noremap! \scu ᴜ
noremap! \scv ᴠ
noremap! \scw ᴡ
noremap! \scy ʏ
noremap! \scz ᴢ
noremap! \wc0 ⓪
noremap! \wc1 ①
noremap! \wc2 ②
noremap! \wc3 ③
noremap! \wc4 ④
noremap! \wc5 ⑤
noremap! \wc6 ⑥
noremap! \wc7 ⑦
noremap! \wc8 ⑧
noremap! \wc9 ⑨
noremap! \wcA Ⓐ
noremap! \wcB Ⓑ
noremap! \wcC Ⓒ
noremap! \wcD Ⓓ
noremap! \wcE Ⓔ
noremap! \wcF Ⓕ
noremap! \wcG Ⓖ
noremap! \wcH Ⓗ
noremap! \wcI Ⓘ
noremap! \wcJ Ⓙ
noremap! \wcK Ⓚ
noremap! \wcL Ⓛ
noremap! \wcM Ⓜ
noremap! \wcN Ⓝ
noremap! \wcO Ⓞ
noremap! \wcP Ⓟ
noremap! \wcQ Ⓠ
noremap! \wcR Ⓡ
noremap! \wcS Ⓢ
noremap! \wcT Ⓣ
noremap! \wcU Ⓤ
noremap! \wcV Ⓥ
noremap! \wcW Ⓦ
noremap! \wcX Ⓧ
noremap! \wcY Ⓨ
noremap! \wcZ Ⓩ
noremap! \wca ⓐ
noremap! \wcb ⓑ
noremap! \wcc ⓒ
noremap! \wcd ⓓ
noremap! \wce ⓔ
noremap! \wcf ⓕ
noremap! \wcg ⓖ
noremap! \wch ⓗ
noremap! \wci ⓘ
noremap! \wcj ⓙ
noremap! \wck ⓚ
noremap! \wcl ⓛ
noremap! \wcm ⓜ
noremap! \wcn ⓝ
noremap! \wco ⓞ
noremap! \wcp ⓟ
noremap! \wcq ⓠ
noremap! \wcr ⓡ
noremap! \wcs ⓢ
noremap! \wct ⓣ
noremap! \wcu ⓤ
noremap! \wcv ⓥ
noremap! \wcw ⓦ
noremap! \wcx ⓧ
noremap! \wcy ⓨ
noremap! \wcz ⓩ
noremap! \A` À
noremap! \A' Á
noremap! \A.. Ä
noremap! \A^ Â
noremap! \C, Ç
noremap! \E` È
noremap! \E' É
noremap! \E^ Ê
noremap! \I' Í
noremap! \I` Ì
noremap! \I.. Ï
noremap! \O^ Ô
noremap! \O.. Ö
noremap! \U' Ú
noremap! \U` Ù
noremap! \U^ Û
noremap! \U.. Ü
noremap! \a` à
noremap! \a' á
noremap! \a.. ä
noremap! \a^ â
noremap! \c, ç
noremap! \e` è
noremap! \e' é
noremap! \e^ ê
noremap! \i' í
noremap! \i` ì
noremap! \i.. ï
noremap! \o^ ô
noremap! \o.. ö
noremap! \u' ú
noremap! \u` ù
noremap! \u^ û
noremap! \u.. ü
noremap! \ae æ
noremap! \oe œ
noremap! \e^~ ễ
noremap! \osl ø
noremap! \Osl Ø
noremap! \osls ᴓ
noremap! \boxlr ─
noremap! \boxLR ━
noremap! \boxtb │
noremap! \boxTB ┃
noremap! \boxlr- ┄
noremap! \boxLR- ┅
noremap! \boxtb- ┆
noremap! \boxTB- ┇
noremap! \boxlr. ┈
noremap! \boxLR. ┉
noremap! \boxtb. ┊
noremap! \boxTB. ┋
noremap! \boxbr ┌
noremap! \boxbR ┍
noremap! \boxBr ┎
noremap! \boxBR ┏
noremap! \boxbl ┐
noremap! \boxbL ┑
noremap! \boxBl ┒
noremap! \boxBL ┓
noremap! \boxtr └
noremap! \boxtR ┕
noremap! \boxTr ┖
noremap! \boxTR ┗
noremap! \boxtl ┘
noremap! \boxtL ┙
noremap! \boxTl ┚
noremap! \boxTL ┛
noremap! \boxtbr ├
noremap! \boxtbR ┝
noremap! \boxTbr ┞
noremap! \boxtBr ┟
noremap! \boxTBr ┠
noremap! \boxTbR ┡
noremap! \boxtBR ┢
noremap! \boxTBR ┣
noremap! \boxtbl ┤
noremap! \boxtbL ┥
noremap! \boxTbl ┦
noremap! \boxtBl ┧
noremap! \boxTBl ┨
noremap! \boxTbL ┩
noremap! \boxtBL ┪
noremap! \boxTBL ┫
noremap! \boxblr ┬
noremap! \boxbLr ┭
noremap! \boxblR ┮
noremap! \boxbLR ┯
noremap! \boxBlr ┰
noremap! \boxBLr ┱
noremap! \boxBlR ┲
noremap! \boxBLR ┳
noremap! \boxtlr ┴
noremap! \boxtLr ┵
noremap! \boxtlR ┶
noremap! \boxtLR ┷
noremap! \boxTlr ┸
noremap! \boxTLr ┹
noremap! \boxTlR ┺
noremap! \boxTLR ┻
noremap! \boxtblr ┼
noremap! \boxtbLr ┽
noremap! \boxtblR ┾
noremap! \boxtbLR ┿
noremap! \boxTblr ╀
noremap! \boxtBlr ╁
noremap! \boxTBlr ╂
noremap! \boxTbLr ╃
noremap! \boxTblR ╄
noremap! \boxtBLr ╅
noremap! \boxtBlR ╆
noremap! \boxTbLR ╇
noremap! \boxtBLR ╈
noremap! \boxTBLr ╉
noremap! \boxTBlR ╊
noremap! \boxTBLR ╋
noremap! \boxlr: ╌
noremap! \boxLR: ╍
noremap! \boxtb: ╎
noremap! \boxTB: ╏
noremap! \boxLR= ═
noremap! \boxTB= ║
noremap! \boxbR= ╒
noremap! \boxBr= ╓
noremap! \boxBR= ╔
noremap! \boxbL= ╕
noremap! \boxBl= ╖
noremap! \boxBL= ╗
noremap! \boxtR= ╘
noremap! \boxTr= ╙
noremap! \boxTR= ╚
noremap! \boxtL= ╛
noremap! \boxTl= ╜
noremap! \boxTL= ╝
noremap! \boxtbR= ╞
noremap! \boxTBr= ╟
noremap! \boxTBR= ╠
noremap! \boxtbL= ╡
noremap! \boxTBl= ╢
noremap! \boxTBL= ╣
noremap! \boxbLR= ╤
noremap! \boxBlr= ╥
noremap! \boxBLR= ╦
noremap! \boxtLR= ╧
noremap! \boxTlr= ╨
noremap! \boxTLR= ╩
noremap! \boxtbLR= ╪
noremap! \boxTBlr= ╫
noremap! \boxTBLR= ╬
noremap! \boxbrc ╭
noremap! \boxblc ╮
noremap! \boxtlc ╯
noremap! \boxtrc ╰
noremap! \boxtrbl ╱
noremap! \boxtlbr ╲
noremap! \boxx ╳
noremap! \boxl ╴
noremap! \boxt ╵
noremap! \boxr ╶
noremap! \boxb ╷
noremap! \boxL ╸
noremap! \boxT ╹
noremap! \boxR ╺
noremap! \boxB ╻
noremap! \boxlR ╼
noremap! \boxtB ╽
noremap! \boxLr ╾
noremap! \boxTb ╿
noremap! \nbsp  
noremap! \ensp  
noremap! \fgsp  
