set iskeyword+=\

" Normal
noremap! \Alpha          Α
noremap! \Beta           Β
noremap! \Gamma          Γ
noremap! \Delta          Δ
noremap! \Epsilon        Ε
noremap! \Zeta           Ζ
noremap! \Eta            Η
noremap! \Theta          Θ
noremap! \Iota           Ι
noremap! \Kappa          Κ
noremap! \Lambda         Λ
noremap! \Mu             Μ
noremap! \Nu             Ν
noremap! \Xi             Ξ
noremap! \Omicron        Ο
noremap! \Pi             Π
noremap! \Rho            Ρ
noremap! \varSigma       ϴ
noremap! \Sigma          Σ
noremap! \Tau            Τ
noremap! \Upsilon        Υ
noremap! \Phi            Φ
noremap! \Chi            Χ
noremap! \Psi            Ψ
noremap! \Omega          Ω
noremap! \Nabla          ∇

noremap! \alpha          α
noremap! \beta           β
noremap! \gamma          γ
noremap! \delta          δ
noremap! \epsilon        ε
noremap! \zeta           ζ
noremap! \eta            η
noremap! \theta          θ
noremap! \iota           ι
noremap! \kappa          κ
noremap! \lambda         λ
noremap! \mu             μ
noremap! \nu             ν
noremap! \xi             ξ
noremap! \omicron        ο
noremap! \pi             π
noremap! \rho            ρ
noremap! \varsigma       ς
noremap! \sigma          σ
noremap! \tau            τ
noremap! \upsilon        υ
noremap! \phi            φ
noremap! \chi            χ
noremap! \psi            ψ
noremap! \omega          ω
noremap! \nabla          ∂

noremap! \varepsilon     ϵ
noremap! \vartheta       ϑ
noremap! \varkappa       ϰ
noremap! \varphi         ϕ
noremap! \varrho         ϱ
noremap! \varpi          ϖ

" Bold

noremap! \bldAlpha         𝚨
noremap! \bldBeta          𝚩
noremap! \bldGamma         𝚪
noremap! \bldDelta         𝚫
noremap! \bldEpsilon       𝚬
noremap! \bldZeta          𝚭
noremap! \bldEta           𝚮
noremap! \bldTheta         𝚯
noremap! \bldIota          𝚰
noremap! \bldKappa         𝚱
noremap! \bldLambda        𝚲
noremap! \bldMu            𝚳
noremap! \bldNu            𝚴
noremap! \bldXi            𝚵
noremap! \bldOmicron       𝚶
noremap! \bldPi            𝚷
noremap! \bldRho           𝚸
noremap! \bldvarSigma      𝚹
noremap! \bldSigma         𝚺
noremap! \bldTau           𝚻
noremap! \bldUpsilon       𝚼
noremap! \bldPhi           𝚽
noremap! \bldChi           𝚾
noremap! \bldPsi           𝚿
noremap! \bldOmega         𝛀
noremap! \bldNabla         𝛁

noremap! \bldalpha         𝛂
noremap! \bldbeta          𝛃
noremap! \bldgamma         𝛄
noremap! \blddelta         𝛅
noremap! \bldepsilon       𝛆
noremap! \bldzeta          𝛇
noremap! \bldldeta         𝛈
noremap! \bldtheta         𝛉
noremap! \bldiota          𝛊
noremap! \bldkappa         𝛋
noremap! \bldlambda        𝛌
noremap! \bldmu            𝛍
noremap! \bldnu            𝛎
noremap! \bldxi            𝛏
noremap! \bldomicron       𝛐
noremap! \bldpi            𝛑
noremap! \bldrho           𝛒
noremap! \bldvarsigma      𝛓
noremap! \bldsigma         𝛔
noremap! \bldtau           𝛕
noremap! \bldupsilon       𝛖
noremap! \bldphi           𝛗
noremap! \bldchi           𝛘
noremap! \bldpsi           𝛙
noremap! \bldomega         𝛚
noremap! \bldnabla         𝛛

noremap! \bvarepsilon      𝛜
noremap! \bvartheta        𝛝
noremap! \bvarkappa        𝛞
noremap! \bvarphi          𝛟
noremap! \bvarrho          𝛠
noremap! \bvarpi           𝛡

" Italic

noremap! \itAlpha         𝛢
noremap! \itBeta          𝛣
noremap! \itGamma         𝛤
noremap! \itDelta         𝛥
noremap! \itEpsilon       𝛦
noremap! \itZeta          𝛧
noremap! \itEta           𝛨
noremap! \itTheta         𝛩
noremap! \itIota          𝛪
noremap! \itKappa         𝛫
noremap! \itLambda        𝛬
noremap! \itMu            𝛭
noremap! \itNu            𝛮
noremap! \itXi            𝛯
noremap! \itOmicron       𝛰
noremap! \itPi            𝛱
noremap! \itRho           𝛲
noremap! \itvarSigma      𝛳
noremap! \itSigma         𝛴
noremap! \itTau           𝛵
noremap! \itUpsilon       𝛶
noremap! \itPhi           𝛷
noremap! \itChi           𝛸
noremap! \itPsi           𝛹
noremap! \itOmega         𝛺
noremap! \itNabla         𝛻

noremap! \italpha         𝛼
noremap! \itbeta          𝛽
noremap! \itgamma         𝛾
noremap! \itdelta         𝛿
noremap! \itepsilon       𝜀
noremap! \itzeta          𝜁
noremap! \iteta           𝜂
noremap! \ittheta         𝜃
noremap! \itiota          𝜄
noremap! \itkappa         𝜅
noremap! \itlambda        𝜆
noremap! \itmu            𝜇
noremap! \itnu            𝜈
noremap! \itxi            𝜉
noremap! \itomicron       𝜊
noremap! \itpi            𝜋
noremap! \itrho           𝜌
noremap! \itvarsigma      𝜍
noremap! \itsigma         𝜎
noremap! \ittau           𝜏
noremap! \itupsilon       𝜐
noremap! \itphi           𝜑
noremap! \itchi           𝜒
noremap! \itpsi           𝜓
noremap! \itomega         𝜔
noremap! \itnabla         𝜕

noremap! \itvarepsilon      𝜖
noremap! \itvartheta        𝜗
noremap! \itvarkappa        𝜘
noremap! \itvarphi          𝜙
noremap! \itvarrho          𝜚
noremap! \itvarpi           𝜛

" Bold Italic

noremap! \blditAlpha        𝜜
noremap! \blditBeta         𝜝
noremap! \blditGamma        𝜞
noremap! \blditDelta        𝜟
noremap! \blditEpsilon      𝜠
noremap! \blditZeta         𝜡
noremap! \blditEta          𝜢
noremap! \blditTheta        𝜣
noremap! \blditIota         𝜤
noremap! \blditKappa        𝜥
noremap! \blditLambda       𝜦
noremap! \blditMu           𝜧
noremap! \blditNu           𝜨
noremap! \blditXi           𝜩
noremap! \blditOmicron      𝜪
noremap! \blditPi           𝜫
noremap! \blditRho          𝜬
noremap! \blditvarSigma     𝜭
noremap! \blditSigma        𝜮
noremap! \blditTau          𝜯
noremap! \blditUpsilon      𝜰
noremap! \blditPhi          𝜱
noremap! \blditChi          𝜲
noremap! \blditPsi          𝜳
noremap! \blditOmega        𝜴
noremap! \blditNabla        𝜵

noremap! \blditalpha        𝜶
noremap! \blditbeta         𝜷
noremap! \blditgamma        𝜸
noremap! \blditdelta        𝜹
noremap! \blditepsilon      𝜺
noremap! \blditzeta         𝜻
noremap! \blditeta          𝜼
noremap! \bldittheta        𝜽
noremap! \blditiota         𝜾
noremap! \blditkappa        𝜿
noremap! \blditlambda       𝝀
noremap! \blditmu           𝝁
noremap! \blditnu           𝝂
noremap! \blditxi           𝝃
noremap! \blditomicron      𝝄
noremap! \blditpi           𝝅
noremap! \blditrho          𝝆
noremap! \blditvarsigma     𝝇
noremap! \blditsigma        𝝈
noremap! \bldittau          𝝉
noremap! \blditupsilon      𝝊
noremap! \blditphi          𝝋
noremap! \blditchi          𝝌
noremap! \blditpsi          𝝍
noremap! \blditomega        𝝎
noremap! \blditnabla        𝝏

noremap! \blditeepsilon     𝝐
noremap! \blditttheta       𝝑
noremap! \blditkkappa       𝝒
noremap! \blditpphi         𝝓
noremap! \blditrrho         𝝔
noremap! \blditppi          𝝕

" subscript
"
noremap! \_beta        ᵦ
noremap! \_gamma       ᵧ
noremap! \_rho         ᵨ
noremap! \_phi         ᵩ
noremap! \_chi         ᵪ

" superscripts

noremap! \^alpha       ᵅ
noremap! \^beta        ᵝ
noremap! \^gamma       ᵞ
noremap! \^delta       ᵟ
noremap! \^epsilon     ᵋ
noremap! \^theta       ᶿ
noremap! \^iota        ᶥ
noremap! \^Phi         ᶲ
noremap! \^phi         ᵠ
noremap! \^chi         ᵡ

" blackboard bold

noremap! \bbGamma        ℾ
noremap! \bbgamma        ℽ
noremap! \bbPi           ℿ
noremap! \bbpi           ℼ
noremap! \bbSigma        ⅀
