set iskeyword+=\

" bold

noremap! \bldA             𝐀
noremap! \bldB             𝐁
noremap! \bldC             𝐂
noremap! \bldD             𝐃
noremap! \bldE             𝐄
noremap! \bldF             𝐅
noremap! \bldG             𝐆
noremap! \bldH             𝐇
noremap! \bldI             𝐈
noremap! \bldJ             𝐉
noremap! \bldK             𝐊
noremap! \bldL             𝐋
noremap! \bldM             𝐌
noremap! \bldN             𝐍
noremap! \bldO             𝐎
noremap! \bldP             𝐏
noremap! \bldQ             𝐐
noremap! \bldR             𝐑
noremap! \bldS             𝐒
noremap! \bldT             𝐓
noremap! \bldU             𝐔
noremap! \bldV             𝐕
noremap! \bldW             𝐖
noremap! \bldX             𝐗
noremap! \bldY             𝐘
noremap! \bldZ             𝐙
noremap! \blda             𝐚
noremap! \bldb             𝐛
noremap! \bldc             𝐜
noremap! \bldd             𝐝
noremap! \blde             𝐞
noremap! \bldf             𝐟
noremap! \bldg             𝐠
noremap! \bldh             𝐡
noremap! \bldi             𝐢
noremap! \bldj             𝐣
noremap! \bldk             𝐤
noremap! \bldl             𝐥
noremap! \bldm             𝐦
noremap! \bldn             𝐧
noremap! \bldo             𝐨
noremap! \bldp             𝐩
noremap! \bldq             𝐪
noremap! \bldr             𝐫
noremap! \blds             𝐬
noremap! \bldt             𝐭
noremap! \bldu             𝐮
noremap! \bldv             𝐯
noremap! \bldw             𝐰
noremap! \bldx             𝐱
noremap! \bldy             𝐲
noremap! \bldz             𝐳

" italic

noremap! \itA             𝐴
noremap! \itB             𝐵
noremap! \itC             𝐶
noremap! \itD             𝐷
noremap! \itE             𝐸
noremap! \itF             𝐹
noremap! \itG             𝐺
noremap! \itH             𝐻
noremap! \itI             𝐼
noremap! \itJ             𝐽
noremap! \itK             𝐾
noremap! \itL             𝐿
noremap! \itM             𝑀
noremap! \itN             𝑁
noremap! \itO             𝑂
noremap! \itP             𝑃
noremap! \itQ             𝑄
noremap! \itR             𝑅
noremap! \itS             𝑆
noremap! \itT             𝑇
noremap! \itU             𝑈
noremap! \itV             𝑉
noremap! \itW             𝑊
noremap! \itX             𝑋
noremap! \itY             𝑌
noremap! \itZ             𝑍
noremap! \ita             𝑎
noremap! \itb             𝑏
noremap! \itc             𝑐
noremap! \itd             𝑑
noremap! \ite             𝑒
noremap! \itf             𝑓
noremap! \itg             𝑔
noremap! \ith             ℎ
noremap! \iti             𝑖
noremap! \itj             𝑗
noremap! \itk             𝑘
noremap! \itl             𝑙
noremap! \itm             𝑚
noremap! \itn             𝑛
noremap! \ito             𝑜
noremap! \itp             𝑝
noremap! \itq             𝑞
noremap! \itr             𝑟
noremap! \its             𝑠
noremap! \itt             𝑡
noremap! \itu             𝑢
noremap! \itv             𝑣
noremap! \itw             𝑤
noremap! \itx             𝑥
noremap! \ity             𝑦
noremap! \itz             𝑧

" bold italic

noremap! \blditA            𝑨
noremap! \blditB            𝑩
noremap! \blditC            𝑪
noremap! \blditD            𝑫
noremap! \blditE            𝑬
noremap! \blditF            𝑭
noremap! \blditG            𝑮
noremap! \blditH            𝑯
noremap! \blditI            𝑰
noremap! \blditJ            𝑱
noremap! \blditK            𝑲
noremap! \blditL            𝑳
noremap! \blditM            𝑴
noremap! \blditN            𝑵
noremap! \blditO            𝑶
noremap! \blditP            𝑷
noremap! \blditQ            𝑸
noremap! \blditR            𝑹
noremap! \blditS            𝑺
noremap! \blditT            𝑻
noremap! \blditU            𝑼
noremap! \blditV            𝑽
noremap! \blditW            𝑾
noremap! \blditX            𝑿
noremap! \blditY            𝒀
noremap! \blditZ            𝒁
noremap! \bldita            𝒂
noremap! \blditb            𝒃
noremap! \blditc            𝒄
noremap! \blditd            𝒅
noremap! \bldite            𝒆
noremap! \blditf            𝒇
noremap! \blditg            𝒈
noremap! \bldith            𝒉
noremap! \blditi            𝒊
noremap! \blditj            𝒋
noremap! \blditk            𝒌
noremap! \blditl            𝒍
noremap! \blditm            𝒎
noremap! \blditn            𝒏
noremap! \bldito            𝒐
noremap! \blditp            𝒑
noremap! \blditq            𝒒
noremap! \blditr            𝒓
noremap! \bldits            𝒔
noremap! \blditt            𝒕
noremap! \blditu            𝒖
noremap! \blditv            𝒗
noremap! \blditw            𝒘
noremap! \blditx            𝒙
noremap! \bldity            𝒚
noremap! \blditz            𝒛

" caligraphy

noremap! \calA             𝒜
noremap! \calB             ℬ
noremap! \calC             𝒞
noremap! \calD             𝒟
noremap! \calE             ℰ
noremap! \calF             ℱ
noremap! \calG             𝒢
noremap! \calH             ℋ
noremap! \calI             ℐ
noremap! \calJ             𝒥
noremap! \calK             𝒦
noremap! \calL             ℒ
noremap! \calM             ℳ
noremap! \calN             𝒩
noremap! \calO             𝒪
noremap! \calP             𝒫
noremap! \calQ             𝒬
noremap! \calR             ℛ
noremap! \calS             𝒮
noremap! \calT             𝒯
noremap! \calU             𝒰
noremap! \calV             𝒱
noremap! \calW             𝒲
noremap! \calX             𝒳
noremap! \calY             𝒴
noremap! \calZ             𝒵
noremap! \cala             𝒶
noremap! \calb             𝒷
noremap! \calc             𝒸
noremap! \cald             𝒹
noremap! \cale             ℯ
noremap! \calf             𝒻
noremap! \calg             ℊ
noremap! \calh             𝒽
noremap! \cali             𝒾
noremap! \calj             𝒿
noremap! \calk             𝓀
noremap! \call             𝓁
noremap! \calm             𝓂
noremap! \caln             𝓃
noremap! \calo             ℴ
noremap! \calp             𝓅
noremap! \calq             𝓆
noremap! \calr             𝓇
noremap! \cals             𝓈
noremap! \calt             𝓉
noremap! \calu             𝓊
noremap! \calv             𝓋
noremap! \calw             𝓌
noremap! \calx             𝓍
noremap! \caly             𝓎
noremap! \calz             𝓏

" bold caligraphy


noremap! \bldcalA            𝓐
noremap! \bldcalB            𝓑
noremap! \bldcalC            𝓒
noremap! \bldcalD            𝓓
noremap! \bldcalE            𝓔
noremap! \bldcalF            𝓕
noremap! \bldcalG            𝓖
noremap! \bldcalH            𝓗
noremap! \bldcalI            𝓘
noremap! \bldcalJ            𝓙
noremap! \bldcalK            𝓚
noremap! \bldcalL            𝓛
noremap! \bldcalM            𝓜
noremap! \bldcalN            𝓝
noremap! \bldcalO            𝓞
noremap! \bldcalP            𝓟
noremap! \bldcalQ            𝓠
noremap! \bldcalR            𝓡
noremap! \bldcalS            𝓢
noremap! \bldcalT            𝓣
noremap! \bldcalU            𝓤
noremap! \bldcalV            𝓥
noremap! \bldcalW            𝓦
noremap! \bldcalX            𝓧
noremap! \bldcalY            𝓨
noremap! \bldcalZ            𝓩
noremap! \bldcala            𝓪
noremap! \bldcalb            𝓫
noremap! \bldcalc            𝓬
noremap! \bldcald            𝓭
noremap! \bldcale            𝓮
noremap! \bldcalf            𝓯
noremap! \bldcalg            𝓰
noremap! \bldcalh            𝓱
noremap! \bldcali            𝓲
noremap! \bldcalj            𝓳
noremap! \bldcalk            𝓴
noremap! \bldcall            𝓵
noremap! \bldcalm            𝓶
noremap! \bldcaln            𝓷
noremap! \bldcalo            𝓸
noremap! \bldcalp            𝓹
noremap! \bldcalq            𝓺
noremap! \bldcalr            𝓻
noremap! \bldcals            𝓼
noremap! \bldcalt            𝓽
noremap! \bldcalu            𝓾
noremap! \bldcalv            𝓿
noremap! \bldcalw            𝔀
noremap! \bldcalx            𝔁
noremap! \bldcaly            𝔂
noremap! \bldcalz            𝔃

" fraktur

noremap! \frakA             𝔄
noremap! \frakB             𝔅
noremap! \frakC             ℭ
noremap! \frakD             𝔇
noremap! \frakE             𝔈
noremap! \frakF             𝔉
noremap! \frakG             𝔊
noremap! \frakH             ℌ
noremap! \frakI             ℑ
noremap! \frakJ             𝔍
noremap! \frakK             𝔎
noremap! \frakL             𝔏
noremap! \frakM             𝔐
noremap! \frakN             𝔑
noremap! \frakO             𝔒
noremap! \frakP             𝔓
noremap! \frakQ             𝔔
noremap! \frakR             ℜ
noremap! \frakS             𝔖
noremap! \frakT             𝔗
noremap! \frakU             𝔘
noremap! \frakV             𝔙
noremap! \frakW             𝔚
noremap! \frakX             𝔛
noremap! \frakY             𝔜
noremap! \frakZ             ℨ
noremap! \fraka             𝔞
noremap! \frakb             𝔟
noremap! \frakc             𝔠
noremap! \frakd             𝔡
noremap! \frake             𝔢
noremap! \frakf             𝔣
noremap! \frakg             𝔤
noremap! \frakh             𝔥
noremap! \fraki             𝔦
noremap! \frakj             𝔧
noremap! \frakk             𝔨
noremap! \frakl             𝔩
noremap! \frakm             𝔪
noremap! \frakn             𝔫
noremap! \frako             𝔬
noremap! \frakp             𝔭
noremap! \frakq             𝔮
noremap! \frakr             𝔯
noremap! \fraks             𝔰
noremap! \frakt             𝔱
noremap! \fraku             𝔲
noremap! \frakv             𝔳
noremap! \frakw             𝔴
noremap! \frakx             𝔵
noremap! \fraky             𝔶
noremap! \frakz             𝔷

" bold fraktur

noremap! \bldfrakA            𝕬
noremap! \bldfrakB            𝕭
noremap! \bldfrakC            𝕮
noremap! \bldfrakD            𝕯
noremap! \bldfrakE            𝕰
noremap! \bldfrakF            𝕱
noremap! \bldfrakG            𝕲
noremap! \bldfrakH            𝕳
noremap! \bldfrakI            𝕴
noremap! \bldfrakJ            𝕵
noremap! \bldfrakK            𝕶
noremap! \bldfrakL            𝕷
noremap! \bldfrakM            𝕸
noremap! \bldfrakN            𝕹
noremap! \bldfrakO            𝕺
noremap! \bldfrakP            𝕻
noremap! \bldfrakQ            𝕼
noremap! \bldfrakR            𝕽
noremap! \bldfrakS            𝕾
noremap! \bldfrakT            𝕿
noremap! \bldfrakU            𝖀
noremap! \bldfrakV            𝖁
noremap! \bldfrakW            𝖂
noremap! \bldfrakX            𝖃
noremap! \bldfrakY            𝖄
noremap! \bldfrakZ            𝖅
noremap! \bldfraka            𝖆
noremap! \bldfrakb            𝖇
noremap! \bldfrakc            𝖈
noremap! \bldfrakd            𝖉
noremap! \bldfrake            𝖊
noremap! \bldfrakf            𝖋
noremap! \bldfrakg            𝖌
noremap! \bldfrakh            𝖍
noremap! \bldfraki            𝖎
noremap! \bldfrakj            𝖏
noremap! \bldfrakk            𝖐
noremap! \bldfrakl            𝖑
noremap! \bldfrakm            𝖒
noremap! \bldfrakn            𝖓
noremap! \bldfrako            𝖔
noremap! \bldfrakp            𝖕
noremap! \bldfrakq            𝖖
noremap! \bldfrakr            𝖗
noremap! \bldfraks            𝖘
noremap! \bldfrakt            𝖙
noremap! \bldfraku            𝖚
noremap! \bldfrakv            𝖛
noremap! \bldfrakw            𝖜
noremap! \bldfrakx            𝖝
noremap! \bldfraky            𝖞
noremap! \bldfrakz            𝖟

" blackboard bold

noremap! \bbA            𝔸
noremap! \bbB            𝔹
noremap! \bbC            ℂ
noremap! \bbD            𝔻
noremap! \bbE            𝔼
noremap! \bbF            𝔽
noremap! \bbG            𝔾
noremap! \bbH            ℍ
noremap! \bbI            𝕀
noremap! \bbJ            𝕁
noremap! \bbK            𝕂
noremap! \bbL            𝕃
noremap! \bbM            𝕄
noremap! \bbN            ℕ
noremap! \bbO            𝕆
noremap! \bbP            ℙ
noremap! \bbQ            ℚ
noremap! \bbR            ℝ
noremap! \bbS            𝕊
noremap! \bbT            𝕋
noremap! \bbU            𝕌
noremap! \bbV            𝕍
noremap! \bbW            𝕎
noremap! \bbX            𝕏
noremap! \bbY            𝕐
noremap! \bbZ            ℤ
noremap! \bba            𝕒
noremap! \bbb            𝕓
noremap! \bbc            𝕔
noremap! \bbd            𝕕
noremap! \bbe            𝕖
noremap! \bbf            𝕗
noremap! \bbg            𝕘
noremap! \bbh            𝕙
noremap! \bbi            𝕚
noremap! \bbj            𝕛
noremap! \bbk            𝕜
noremap! \bbl            𝕝
noremap! \bbm            𝕞
noremap! \bbn            𝕟
noremap! \bbo            𝕠
noremap! \bbp            𝕡
noremap! \bbq            𝕢
noremap! \bbr            𝕣
noremap! \bbs            𝕤
noremap! \bbt            𝕥
noremap! \bbu            𝕦
noremap! \bbv            𝕧
noremap! \bbw            𝕨
noremap! \bbx            𝕩
noremap! \bby            𝕪
noremap! \bbz            𝕫

" subscript

noremap! \_a           ₐ
noremap! \_e           ₑ
noremap! \_h           ₕ
noremap! \_i           ᵢ
noremap! \_j           ⱼ
noremap! \_k           ₖ
noremap! \_l           ₗ
noremap! \_m           ₘ
noremap! \_n           ₙ
noremap! \_o           ₒ
noremap! \_p           ₚ
noremap! \_r           ᵣ
noremap! \_s           ₛ
noremap! \_t           ₜ
noremap! \_u           ᵤ
noremap! \_v           ᵥ
noremap! \_x           ₓ

" superscript

noremap! \^A           ᴬ
noremap! \^B           ᴮ
noremap! \^D           ᴰ
noremap! \^E           ᴱ
noremap! \^G           ᴳ
noremap! \^H           ᴴ
noremap! \^I           ᴵ
noremap! \^J           ᴶ
noremap! \^K           ᴷ
noremap! \^L           ᴸ
noremap! \^M           ᴹ
noremap! \^N           ᴺ
noremap! \^O           ᴼ
noremap! \^P           ᴾ
noremap! \^R           ᴿ
noremap! \^T           ᵀ
noremap! \^U           ᵁ
noremap! \^V           ⱽ
noremap! \^W           ᵂ
noremap! \^a           ᵃ
noremap! \^b           ᵇ
noremap! \^c           ᶜ
noremap! \^d           ᵈ
noremap! \^e           ᵉ
noremap! \^f           ᶠ
noremap! \^g           ᵍ
noremap! \^h           ʰ
noremap! \^i           ⁱ
noremap! \^j           ʲ
noremap! \^k           ᵏ
noremap! \^l           ˡ
noremap! \^m           ᵐ
noremap! \^n           ⁿ
noremap! \^o           ᵒ
noremap! \^p           ᵖ
noremap! \^r           ʳ
noremap! \^s           ˢ
noremap! \^t           ᵗ
noremap! \^u           ᵘ
noremap! \^v           ᵛ
noremap! \^w           ʷ
noremap! \^x           ˣ
noremap! \^y           ʸ
noremap! \^z           ᶻ

" smallcaps

noremap! \smallA       ᴀ
noremap! \smallB       ʙ
noremap! \smallC       ᴄ
noremap! \smallD       ᴅ
noremap! \smallE       ᴇ
noremap! \smallF       ꜰ
noremap! \smallG       ɢ
noremap! \smallH       ʜ
noremap! \smallI       ɪ
noremap! \smallJ       ᴊ
noremap! \smallK       ᴋ
noremap! \smallL       ʟ
noremap! \smallM       ᴍ
noremap! \smallN       ɴ
noremap! \smallO       ᴏ
noremap! \smallP       ᴘ
noremap! \smallR       ʀ
noremap! \smallS       ꜱ
noremap! \smallT       ᴛ
noremap! \smallU       ᴜ
noremap! \smallV       ᴠ
noremap! \smallW       ᴡ
noremap! \smallY       ʏ
noremap! \smallZ       ᴢ
